/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-10-18 10:03:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.signup;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/jsp/signup/../common/footer.jsp", Long.valueOf(1665638226418L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1601362911995L));
    _jspx_dependants.put("/WEB-INF/jsp/signup/../common/headerBase.jsp", Long.valueOf(1666082905071L));
    _jspx_dependants.put("jar:file:/C:/Users/simpl/workspace_kfors/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/frwk/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/jsp/signup/../common/top.jsp", Long.valueOf(1666072134445L));
    _jspx_dependants.put("/WEB-INF/jsp/signup/../common/bottom.jsp", Long.valueOf(1665638226110L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--공통헤더-->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>JOB119 - 소방전문가 취업 플랫폼</title>\r\n");
      out.write("    <script src=\"/js/lib/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/common.css\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/additional-methods.min.js\"></script>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/join.css\">\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<article class=\"ad-top\">\r\n");
      out.write("    <div class=\"ad-top__close-btn\">\r\n");
      out.write("        <p>오늘 하루 보지 않기</p>\r\n");
      out.write("        <input type=\"checkbox\" />\r\n");
      out.write("    </div>\r\n");
      out.write("</article>\r\n");
      out.write("<header class=\"header-d\">\r\n");
      out.write("    <section class=\"head-wrap\">\r\n");
      out.write("        <h1 class=\"logo\">\r\n");
      out.write("            <a href=\"/\" class=\"logo__link\">\r\n");
      out.write("                <img src=\"/img/logo.svg\" alt=\"로고\" />\r\n");
      out.write("            </a>\r\n");
      out.write("        </h1>\r\n");
      out.write("        <div class=\"search-area\">\r\n");
      out.write("            <div class=\"search-bar\">\r\n");
      out.write("                <button type=\"button\" class=\"search-bar__search-btn\"></button>\r\n");
      out.write("                <input type=\"text\" class=\"search-bar__textbar\" />\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"user-info\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <nav class=\"head-nav\">\r\n");
      out.write("        <ul class=\"head-nav__depth-01\">\r\n");
      out.write("            <li class=\"sitemap head-nav__item-01\"><a href=\"#\">전체메뉴</a></li>\r\n");
      out.write("            <li class=\"head-nav__item-01 list-01\"><a href=\"#\">채용정보</a></li>\r\n");
      out.write("            <li class=\"head-nav__item-01 list-02\"><a href=\"#\">인재정보</a></li>\r\n");
      out.write("            <li class=\"head-nav__item-01\"><a href=\"#\">취업서비스</a></li>\r\n");
      out.write("            <li class=\"head-nav__item-01\"><a href=\"#\">맞춤정보</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"head-btn\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mega-menu all-menu sitemenu\">\r\n");
      out.write("            <div class=\"mega-menu__row all-menu__row\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p class=\"mega-menu__title all-menu__title\">전체메뉴</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>채용정보</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">일반채용</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">지역별 채용</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">분류별 채용</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">조건별 채용</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">맞춤 정보</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>인재정보</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">일반인재</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">전문인재</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">능력별인재</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">맞춤 정보</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>취업서비스</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">적성검사</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">채용광고상품</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>고객지원</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">공지사항</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">자주묻는질문</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">공고등록대행 안내</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">온라인 문의</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">채용서비스 안내</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">제휴 및 배너광고 문의</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">이용약관</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">개인정보처리방침</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">위치기반서비스 이용약관</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mega-menu all-menu menu-01\">\r\n");
      out.write("            <div class=\"mega-menu__row all-menu__row\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p class=\"mega-menu__title all-menu__title\">채용정보</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>일반채용</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">전체 채용공고</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">오늘 등록정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">마감임박 채용정보</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>지역별 채용</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02 all-menu__divide\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">전국</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">부산</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">대전</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">대구</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">세종</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">강원</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">충남</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">전남</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">경남</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">서울</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">인천</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">광주</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">울산</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">경기</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">충북</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">전북</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">경북</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">제주</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>분류별 채용</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">업종(소방)</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">업종(일반)</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">직무</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">자격</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>조건별 채용</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">고용형태</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">기업분류</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">직급/직책</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">우대사항</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">복리후생</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>맞춤 정보</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">맞춤 채용정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">스크랩 채용정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">오늘본 채용정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">맞춤 설정</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mega-menu all-menu menu-02\">\r\n");
      out.write("            <div class=\"mega-menu__row all-menu__row\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p class=\"mega-menu__title all-menu__title\">인재정보</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>일반인재</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">전체 인재정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">오늘 등록정보</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>전문인재</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">소방 자격증</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">소방관 근무경력</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">해외 근무경력</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">외국어 가능</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>능력별 인재</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">자격증별 인재</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">외국어가능별 인재</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">지역별 인재</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">경력조건별 인재</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>맞춤 정보</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">맞춤 채용정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">오늘본 인재정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">스크랩 인재정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">맞춤 설정</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"all-menu__bg\"></div>\r\n");
      out.write("</header>\r\n");
      out.write("<header class=\"header-m\">\r\n");
      out.write("    <section class=\"head-wrap\">\r\n");
      out.write("        <h1 class=\"logo\">\r\n");
      out.write("            <a href=\"#\" class=\"logo__link\">\r\n");
      out.write("                <img src=\"/img/logo.svg\" alt=\"로고\" />\r\n");
      out.write("            </a>\r\n");
      out.write("        </h1>\r\n");
      out.write("        <button type=\"button\" class=\"head-wrap__m-btn\"></button>\r\n");
      out.write("    </section>\r\n");
      out.write("    <nav class=\"m-nav\">\r\n");
      out.write("        <div class=\"m-nav__top\">\r\n");
      out.write("            <div class=\"user-info\">\r\n");
      out.write("                <a href=\"#\" class=\"user-info__login\">로그인</a>\r\n");
      out.write("                <a href=\"#\" class=\"user-info__join\">회원가입</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"button\" class=\"m-nav__close\"></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"m-nav__depth-01\">\r\n");
      out.write("            <li class=\"m-nav__item-01\"><a href=\"#\">채용정보</a>\r\n");
      out.write("                <ul class=\"m-nav__depth-02\">\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">일반 채용</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">지역별 채용</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">분류별 채용</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">조건별 채용</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">맞춤 정보</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"m-nav__item-01\"><a href=\"#\">인재정보</a>\r\n");
      out.write("                <ul class=\"m-nav__depth-02\">\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">일반 인재</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">전문 인재</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">능력별 인재</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">맞춤 정보</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"m-nav__item-01\"><a href=\"#\">취업서비스</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"m-nav__item-01\"><a href=\"#\">고객지원</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"m-nav__head-btn\">\r\n");
      out.write("            <button type=\"button\" class=\"primary_btn_icon ico_resume\" onclick=\"location.href='/psn/resume/registration.do';\">이력서 등록</button>\r\n");
      out.write("            <button type=\"button\" class=\"sub_btn_icon ico_hire\" onclick=\"location.href='/com/jobopen/registration.do';\">채용공고 등록</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<main class=\"main\">\r\n");
      out.write("        <section class=\"main__wrap w-600\">\r\n");
      out.write("            <article class=\"user\">\r\n");
      out.write("            	<form name=\"frmPsnSignup\" id=\"frmPsnSignup\" method=\"post\" action=\"/doSignup.do\" novalidate=\"novalidate\">\r\n");
      out.write("            	<input type=\"hidden\" name=\"userType\" value=\"PERSONAL\">\r\n");
      out.write("                <div class=\"tab\">\r\n");
      out.write("                    <button type=\"button\" class=\"tab__item active user_btn\">개인회원</button>\r\n");
      out.write("                    <button type=\"button\" class=\"tab__item conp_btn\">기업회원</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"join__row\">\r\n");
      out.write("                    <h3 class=\"join__title\">소셜 간편 로그인</h3>\r\n");
      out.write("                    <div class=\"social\">\r\n");
      out.write("                        <button type=\"button\" class=\"social__btn naver\" data-name=\"네이버 로그인\"></button>\r\n");
      out.write("                        <button type=\"button\" class=\"social__btn kakao\" data-name=\"카카오 로그인\"></button>\r\n");
      out.write("                        <button type=\"button\" class=\"social__btn google\" data-name=\"구글 로그인\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"join__row\">\r\n");
      out.write("	                    <h3 class=\"join__title\" data-text=\"*필수정보 입력입니다.\">개인정보 입력</h3>\r\n");
      out.write("	                    <div class=\"join__row put_text\">\r\n");
      out.write("	                        <p class=\"emphasis title\">아이디</p>\r\n");
      out.write("	                        <input type=\"text\" name=\"userId\" placeholder=\"8~12자의 영문,숫자,특수문자만\" custom=\"아이디\">\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <p class=\"notice_text notice_text__warnning\" style=\"display: none;\">8~12자의 영문,숫자,특수문자만 가능합니다.</p>\r\n");
      out.write("	                    <div class=\"join__row put_text\">\r\n");
      out.write("	                        <p class=\"emphasis title\">비밀번호</p>\r\n");
      out.write("	                        <input type=\"password\" name=\"userPw\" placeholder=\"8~12자의 영문,숫자,특수문자 중 3가지 이상 조합\" maxlength=\"12\" custom=\"패스워드\">\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <p class=\"notice_text notice_text__warnning\" style=\"display: none;\">유효하지 않은 비밀번호 입니다.</p>\r\n");
      out.write("	                    <div class=\"join__row put_text\">\r\n");
      out.write("	                        <p class=\"emphasis title\">이름</p>\r\n");
      out.write("	                        <input type=\"text\" name=\"userNm\" custom=\"이름\">\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"join__row put_text\">\r\n");
      out.write("	                        <p class=\"emphasis title\">휴대전화</p>\r\n");
      out.write("	                        <div class=\"include\">\r\n");
      out.write("	                            <input type=\"text\" name=\"userPhn\" placeholder=\"‘-’ 없이 입력\"  onKeyup=\"this.value=this.value.replace(/[^0-9]/g,'');\" maxlength=\"12\" custom=\"휴대전화\">\r\n");
      out.write("	                            <button type=\"button\" class=\"primary_btn\">본인인증</button>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"join__row put_text\">\r\n");
      out.write("	                        <p class=\"emphasis title\">생년월일</p>\r\n");
      out.write("	                        <input type=\"text\" name=\"userBirth\" placeholder=\"YYYYMMDD (예:19991231)\" onKeyup=\"this.value=this.value.replace(/[^0-9]/g,'');\" maxlength=\"8\" custom=\"생년월일\">\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"join__row put_text\">\r\n");
      out.write("	                        <p class=\"emphasis title\">성별</p>\r\n");
      out.write("	                        <div class=\"include flex_left\">\r\n");
      out.write("	                            <label class=\"check\">\r\n");
      out.write("	                                <input type=\"radio\" name=\"userSex\" value=\"M\" custom=\"성별\"/>\r\n");
      out.write("	                                <p class=\"w-radio\">남자</p>\r\n");
      out.write("	                            </label>\r\n");
      out.write("	                            <label class=\"check\">\r\n");
      out.write("	                                <input type=\"radio\" name=\"userSex\" value=\"F\" custom=\"성별\"/>\r\n");
      out.write("	                                <p class=\"w-radio\">여자</p>\r\n");
      out.write("	                            </label>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"join__row put_text\">\r\n");
      out.write("	                        <p class=\"emphasis title\">이메일</p>\r\n");
      out.write("	                        <div class=\"include\">\r\n");
      out.write("	                            <input type=\"text\" name=\"userEmailId\"  custom=\"이메일\"/>\r\n");
      out.write("	                            <p class=\"email\">@</p>\r\n");
      out.write("	                            <select name=\"userEmail\">\r\n");
      out.write("	                                <option>naver.com</option>\r\n");
      out.write("	                                <option>daum.com</option>\r\n");
      out.write("	                                <option>google.com</option>\r\n");
      out.write("	                                <option>nate.com</option>\r\n");
      out.write("	                            </select>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"join__row put_text\">\r\n");
      out.write("	                        <p class=\"emphasis title\">주소</p>\r\n");
      out.write("	                        <div class=\"add_text\">\r\n");
      out.write("	                            <div class=\"include\">\r\n");
      out.write("	                                <input type=\"text\" name=\"userZipCd\" placeholder=\"우편번호\" custom=\"우편번호\" readonly>\r\n");
      out.write("	                                <button type=\"button\" class=\"primary_btn\" onclick=\"findAddress('PERSONAL')\">주소찾기</button>\r\n");
      out.write("	                            </div>\r\n");
      out.write("	                            <input type=\"text\" name=\"userAddr\" placeholder=\"도로명 주소\" custom=\"도로명 주소\" readonly>\r\n");
      out.write("	                            <input type=\"text\" name=\"userDetailAddr\" placeholder=\"상세 주소\" custom=\"상세 주소\">\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"join__row put_text\">\r\n");
      out.write("	                        <p class=\"title\">퇴직소방관 인증</p>\r\n");
      out.write("	                        <div class=\"include\">\r\n");
      out.write("	                            <input type=\"file\" id=\"userInputFile\" name=\"userInputFile\"  style=\"display:none;\" onchange=\"changeValue(this,'user')\"/>\r\n");
      out.write("	                            <input type=\"text\" id=\"userFileName\" name=\"userFileName\" placeholder=\"파일을 선택해 주세요.\" />\r\n");
      out.write("	                            <button type=\"button\" id=\"userBtnUpload\" class=\"primary_btn\">파일선택</button>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <p class=\"notice_text\"><span>3개월 이내의</span> 퇴직(경력)증명서를 첨부해 주세요.</p>\r\n");
      out.write("	                    <div class=\"join__row put_text\">\r\n");
      out.write("	                        <p class=\"info_text\">퇴직(전직) 소방관님은<br>반드시 퇴직(경력)증명서를 제출해 주세요.<br>경력 인증절차를 거쳐 별도의 전문인재관리 시스템에 등록됩니다.</p>\r\n");
      out.write("	                        <div class=\"join__btns\">\r\n");
      out.write("	                            <button type=\"button\" class=\"accent_btn\" onclick=\"window.open('https://www.gov.kr/mw/AA020InfoCappView.do?CappBizCD=00000000008')\">경력증명서 발급<br>받으러 가기</button>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"join__row\">\r\n");
      out.write("                    <h3 class=\"join__title\">약관 동의</h3>\r\n");
      out.write("                    <div class=\"check_area\">\r\n");
      out.write("                        <div class=\"top\">\r\n");
      out.write("                            <label class=\"check\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"chkAll\" name=\"chkAll\"/>\r\n");
      out.write("                                <p>이용약관에 모두 동의합니다.</p>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <hr>\r\n");
      out.write("                            <label class=\"check\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"chkSub\" name=\"chkAge\" custom=\"필수동의 항목\"/>\r\n");
      out.write("                                <p><span class=\"check__red\">[필수]</span>만 15세 이상입니다.</p>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"check\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"chkSub\" name=\"chkService\" custom=\"필수동의 항목\"/>\r\n");
      out.write("                                <p><span class=\"check__red\">[필수]</span>서비스 이용약관 동의</p>\r\n");
      out.write("                                <button type=\"button\" class=\"primary_btn_line_s check__detail\">세부내용</button>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"check\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"chkSub\" name=\"chkPrivacy\" custom=\"필수동의 항목\"/>\r\n");
      out.write("                                <p><span class=\"check__red\">[필수]</span>개인정보 수집 및 이용 동의</p>\r\n");
      out.write("                                <button type=\"button\" class=\"primary_btn_line_s check__detail\">세부내용</button>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"check\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"chkSub\" name=\"chkPrivacyOptional\"/>\r\n");
      out.write("                                <p>[선택] 개인정보 수집 및 이용 동의</p>\r\n");
      out.write("                                <button type=\"button\" class=\"primary_btn_line_s check__detail\">세부내용</button>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"check\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"chkSub\" name=\"chkSms\"/>\r\n");
      out.write("                                <p>[선택] 광고성 정보 수신 동의 (SMS)</p>\r\n");
      out.write("                                <button type=\"button\" class=\"primary_btn_line_s check__detail\">세부내용</button>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"check\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"chkSub\" name=\"chkEmail\"/>\r\n");
      out.write("                                <p>[선택] 광고성 정보 수신 동의 (이메일)</p>\r\n");
      out.write("                                <button type=\"button\" class=\"primary_btn_line_s check__detail\">세부내용</button>\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"join__row\">\r\n");
      out.write("                    <h3 class=\"join__title\">개인정보 유효기간 선택</h3>\r\n");
      out.write("                    <div class=\"include flex_left\">\r\n");
      out.write("                    <div class=\"check_area check_area__flex\">\r\n");
      out.write("                        <label class=\"check\">\r\n");
      out.write("                            <input type=\"radio\" name=\"validity\" value=\"1\" custom=\"개인정보 유효기간\"/>\r\n");
      out.write("                            <p>1년</p>\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <label class=\"check\">\r\n");
      out.write("                            <input type=\"radio\" name=\"validity\" value=\"3\" custom=\"개인정보 유효기간\"/>\r\n");
      out.write("                            <p>3년</p>\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <label class=\"check\">\r\n");
      out.write("                            <input type=\"radio\" name=\"validity\" value=\"5\" custom=\"개인정보 유효기간\"/>\r\n");
      out.write("                            <p>5년</p>\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <label class=\"check\">\r\n");
      out.write("                            <input type=\"radio\" name=\"validity\" value=\"0\" custom=\"개인정보 유효기간\"/>\r\n");
      out.write("                            <p>회원탈퇴시</p>\r\n");
      out.write("                        </label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"join__row join__btns\">\r\n");
      out.write("                    <button type=\"button\" class=\"primary_btn_line\" onclick=\"location.href='/index.do';\">취소</button>\r\n");
      out.write("                    <!-- <button type=\"submit\" class=\"primary_btn\" form=\"frmPsnSignup\">가입하기</button> -->\r\n");
      out.write("                    <button type=\"submit\" class=\"primary_btn\" >가입하기</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </article>\r\n");
      out.write("            <article class=\"company\" style=\"display: none;\">\r\n");
      out.write("            	<form name=\"frmComSignup\" id=\"frmComSignup\" method=\"post\" action=\"/doSignup.do\" novalidate=\"novalidate\">\r\n");
      out.write("            	<input type=\"hidden\" name=\"userType\" value=\"COMPANY\">\r\n");
      out.write("                <div class=\"tab\">\r\n");
      out.write("                    <button type=\"button\" class=\"tab__item user_btn active\">개인회원</button>\r\n");
      out.write("                    <button type=\"button\" class=\"tab__item conp_btn\">기업회원</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"join__row\">\r\n");
      out.write("                    <h3 class=\"join__title\" data-text=\"*필수정보 입력입니다.\">기업정보 입력</h3>\r\n");
      out.write("                    <div class=\"join__row put_text\">\r\n");
      out.write("                        <p class=\"emphasis title\">사업자 등록번호</p>\r\n");
      out.write("                        <input type=\"text\" name=\"bizrno\" placeholder=\"사업자등록번호 입력 (10자리 숫자만)\" custom=\"사업자 등록번호\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"notice_text notice_text__warnning\" style=\"display: none;\">사업등록번호 확인완료, 사업자등록증(증명원) 내용을 입력해주세요.</p>\r\n");
      out.write("                    <div class=\"join__row put_text\">\r\n");
      out.write("                        <p class=\"emphasis title\">기업명</p>\r\n");
      out.write("                        <input type=\"text\" name=\"conpNm\" placeholder=\"사업자등록증명원 기업명 기재\" custom=\"기업명\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"join__row put_text\">\r\n");
      out.write("                        <p class=\"emphasis title\">대표자명</p>\r\n");
      out.write("                        <input type=\"text\" name=\"conpCeo\" placeholder=\"사업자등록증명원 대표자명 기재\" custom=\"대표자명\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"join__row put_text\">\r\n");
      out.write("                        <p class=\"emphasis title\">회사 주소</p>\r\n");
      out.write("                        <div class=\"add_text\">\r\n");
      out.write("                            <div class=\"include\">\r\n");
      out.write("                                <input type=\"text\" name=\"conpZipCd\" placeholder=\"우편번호\" custom=\"우편번호\" readonly custom=\"우편번호\">\r\n");
      out.write("                                <button type=\"button\" class=\"primary_btn\" onclick=\"findAddress('COMPANY')\">주소찾기</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <input type=\"text\" name=\"conpAddr\" placeholder=\"도로명 주소\" custom=\"도로명 주소\" readonly custom=\"도로명 주소\">\r\n");
      out.write("                            <input type=\"text\" name=\"conpDetailAddr\" placeholder=\"상세 주소\" custom=\"상세 주소\" custom=\"상세 주소\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"join__row put_text\">\r\n");
      out.write("                        <p class=\"emphasis title\">기업 인증</p>\r\n");
      out.write("                        <div class=\"include\">\r\n");
      out.write("	                        <input type=\"file\" id=\"conpInputFile\" name=\"conpInputFile\"  style=\"display:none;\" onchange=\"changeValue(this,'conp')\" />\r\n");
      out.write("	                        <input type=\"text\" id=\"conpFileName\" name=\"conpFileName\" placeholder=\"파일을 선택해 주세요.\" custom=\"기업 인증\"/>\r\n");
      out.write("	                        <button type=\"button\" id=\"confBtnUpload\" class=\"primary_btn\">파일선택</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"notice_text\"><span>3개월 이내의</span> 사업자등록증명원을 첨부해 주세요.</p>\r\n");
      out.write("                    <button type=\"button\" class=\"accent_btn orange_btn\" onclick=\"window.open('https://www.gov.kr/mw/AA020InfoCappView.do?HighCtgCD=&CappBizCD=12100000016')\">사업자등록 증명원 발급 받으러 가기</button>\r\n");
      out.write("                    <div class=\"join__row put_text\">\r\n");
      out.write("                        <p class=\"emphasis title\">로고등록</p>\r\n");
      out.write("                        <div class=\"include\">\r\n");
      out.write("	                        <input type=\"file\" id=\"logoInputFile\" name=\"logoInputFile\"  style=\"display:none;\" onchange=\"changeValue(this,'logo')\" />\r\n");
      out.write("	                        <input type=\"text\" id=\"logoFileName\" name=\"logoFileName\" placeholder=\"파일을 선택해 주세요.\" custom=\"로고등록\"/>\r\n");
      out.write("	                        <button type=\"button\" id=\"logoBtnUpload\" class=\"primary_btn\">파일선택</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"join__row\">\r\n");
      out.write("                    <h3 class=\"join__title\">약관 동의</h3>\r\n");
      out.write("                    <div class=\"check_area\">\r\n");
      out.write("                        <div class=\"top\">\r\n");
      out.write("                            <label class=\"check\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"chkConpAll\" name=\"chkConpAll\"/>\r\n");
      out.write("                                <p>이용약관에 모두 동의합니다.</p>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <hr>\r\n");
      out.write("                            <label class=\"check\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"chkConpSub\" name=\"chkConpService\" custom=\"필수동의 항목\"/>\r\n");
      out.write("                                <p><span class=\"check__red\">[필수]</span>서비스 이용약관 동의</p>\r\n");
      out.write("                                <button type=\"button\" class=\"primary_btn_line_s check__detail\">세부내용</button>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"check\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"chkConpSub\" name=\"chkConpPrivacy\" custom=\"필수동의 항목\"/>\r\n");
      out.write("                                <p><span class=\"check__red\">[필수]</span>개인정보 수집 및 이용 동의</p>\r\n");
      out.write("                                <button type=\"button\" class=\"primary_btn_line_s check__detail\">세부내용</button>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"check\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"chkConpSub\" name=\"chkConpSms\"  />\r\n");
      out.write("                                <p>[선택] 광고성 정보 수신 동의 (SMS)</p>\r\n");
      out.write("                                <button type=\"button\" class=\"primary_btn_line_s check__detail\">세부내용</button>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"check\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"chkConpSub\" name=\"chkConpEmail\"  />\r\n");
      out.write("                                <p>[선택] 광고성 정보 수신 동의 (이메일)</p>\r\n");
      out.write("                                <button type=\"button\" class=\"primary_btn_line_s check__detail\">세부내용</button>\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"join__row\">\r\n");
      out.write("                    <h3 class=\"join__title\">기업정보 유효기간 선택</h3>\r\n");
      out.write("                    <div class=\"check_area check_area__flex\">\r\n");
      out.write("                        <label class=\"check\">\r\n");
      out.write("                            <input type=\"radio\" name=\"validityConp\" value=\"1\" custom=\"개인정보 유효기간\"/>\r\n");
      out.write("                            <p>1년</p>\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <label class=\"check\">\r\n");
      out.write("                            <input type=\"radio\" name=\"validityConp\" value=\"3\" custom=\"개인정보 유효기간\"/>\r\n");
      out.write("                            <p>3년</p>\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <label class=\"check\">\r\n");
      out.write("                            <input type=\"radio\" name=\"validityConp\" value=\"5\" custom=\"개인정보 유효기간\"/>\r\n");
      out.write("                            <p>5년</p>\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <label class=\"check\">\r\n");
      out.write("                            <input type=\"radio\" name=\"validityConp\" value=\"0\" custom=\"개인정보 유효기간\"/>\r\n");
      out.write("                            <p>회원탈퇴시</p>\r\n");
      out.write("                        </label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"join__row\">\r\n");
      out.write("                    <h3 class=\"join__title\" data-text=\"*필수정보 입력입니다.\">인사담당자 정보</h3>\r\n");
      out.write("                    <div class=\"join__row put_text\">\r\n");
      out.write("                        <p class=\"emphasis title\">아이디</p>\r\n");
      out.write("                        <input type=\"text\" name=\"conpId\" placeholder=\"8~12자의 영문,숫자,특수문자만\" custom=\"아이디\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"notice_text notice_text__warnning\" style=\"display: none;\">유효하지 않은 아이디입니다.</p>\r\n");
      out.write("                    <div class=\"join__row put_text\">\r\n");
      out.write("                        <p class=\"emphasis title\">비밀번호</p>\r\n");
      out.write("                        <input type=\"password\" name=\"conpPW\" placeholder=\"8~12자의 영문,숫자,특수문자 중 3가지 이상 조합\" custom=\"비밀번호\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"notice_text notice_text__warnning\" style=\"display: none;\">유효하지 않은 비밀번호 입니다.</p>\r\n");
      out.write("                    <div class=\"join__row put_text\">\r\n");
      out.write("                        <p class=\"emphasis title\">담당자명</p>\r\n");
      out.write("                        <input type=\"text\" name=\"picNm\" custom=\"담당자명\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"join__row put_text\">\r\n");
      out.write("                        <p class=\"emphasis title\">담당자 연락처</p>\r\n");
      out.write("                        <div class=\"include\">\r\n");
      out.write("                            <input type=\"text\" name=\"picPhn\" placeholder=\"핸드폰 번호 ‘-’ 없이 입력\" custom=\"담당자 연락처\">\r\n");
      out.write("                            <button type=\"button\"  class=\"primary_btn\">본인인증</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"join__row put_text\">\r\n");
      out.write("                        <p class=\"emphasis title\">담당자 이메일</p>\r\n");
      out.write("                        <div class=\"include\">\r\n");
      out.write("                        	<input type=\"text\" name=\"picEmailId\"  custom=\"이메일\"/>\r\n");
      out.write("                            <p class=\"email\">@</p>\r\n");
      out.write("                            <select name=\"picEmail\">\r\n");
      out.write("                                <option>naver.com</option>\r\n");
      out.write("                                <option>daum.com</option>\r\n");
      out.write("                                <option>google.com</option>\r\n");
      out.write("                                <option>nate.com</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"join__row put_text\">\r\n");
      out.write("                        <p class=\"emphasis title\">담당 부서명</p>\r\n");
      out.write("                        <input type=\"text\" name=\"picDep\" custom=\"담당 부서명\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"join__row put_text\">\r\n");
      out.write("                        <p class=\"emphasis title\">담당자 직급</p>\r\n");
      out.write("                        <input type=\"text\" name=\"picRank\" custom=\"담당자 직급\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"join__row put_text\">\r\n");
      out.write("                        <p class=\"emphasis title\">회사전화번호</p>\r\n");
      out.write("                        <input type=\"text\" name=\"picTel\" placeholder=\"예 : 02-123-1234\" custom=\"회사전화번호\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"join__row put_text\">\r\n");
      out.write("                        <p class=\"emphasis title\">회사팩스번호</p>\r\n");
      out.write("                        <input type=\"text\" name=\"picFax\" placeholder=\"예 : 02-123-1234\" custom=\"회사팩스번호\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"join__row put_text\">\r\n");
      out.write("                        <p class=\"emphasis title\">연락처 노출구분</p>\r\n");
      out.write("                        <div class=\"include flex_left check_btns\">\r\n");
      out.write("                            <label class=\"check\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"openYn\" name=\"phnYn\"/>\r\n");
      out.write("                                <p class=\"w-radio\">핸드폰 공개</p>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"check\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"openYn\" name=\"telYn\"/>\r\n");
      out.write("                                <p class=\"w-radio\">전화번호 공개</p>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <label class=\"check\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"openYn\" name=\"emailYn\"/>\r\n");
      out.write("                                <p class=\"w-radio\">이메일 공개</p>\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"join__row join__btns\">\r\n");
      out.write("                    <button type=\"button\" class=\"primary_btn_line\">취소</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"primary_btn\">가입하기</button>\r\n");
      out.write("                </div>\r\n");
      out.write("				</form>\r\n");
      out.write("            </article>\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("<!--공통푸터-->\n");
      out.write("<footer>\n");
      out.write("    <section class=\"foot-row\">\n");
      out.write("        <div class=\"foot-row__wrap\">\n");
      out.write("            <div class=\"foot-row__btn-wrap\">\n");
      out.write("                <button type=\"button\" class=\"foot-row__btn\">\n");
      out.write("                    <img src=\"/img/ico_question.png\" alt=\"자주묻는질문 버튼\">\n");
      out.write("                    자주 묻는 질문</button>\n");
      out.write("                <button type=\"button\" class=\"foot-row__btn\">\n");
      out.write("                    <img src=\"/img/ico_ad.png\" alt=\"공고대행안내 버튼\">\n");
      out.write("                    공고대행 안내</button>\n");
      out.write("                <button type=\"button\" class=\"foot-row__btn\">\n");
      out.write("                    <img src=\"/img/ico_online.png\" alt=\"온라인문의 버튼\">\n");
      out.write("                    온라인 문의</button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"foot-row__num\">\n");
      out.write("                <p>고객센터</p>\n");
      out.write("                <p>1588-0000</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"foot-row__siste-info\">\n");
      out.write("                <p>평일 10:00 ~ 16:00</p>\n");
      out.write("                <p>주말·공휴일 휴무</p>\n");
      out.write("                <p>이메일 helpdesk@firework.or.kr</p>\n");
      out.write("                <p>팩스 02-XXXX-XXXX</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <section class=\"foot-row--bg\">\n");
      out.write("        <div class=\"foot-row__wrap\">\n");
      out.write("            <nav class=\"foot-row__nav\">\n");
      out.write("                <ul>\n");
      out.write("                    <li><a href=\"#\">사이트맵</a></li>\n");
      out.write("                    <li><a href=\"#\">상품안내</a></li>\n");
      out.write("                    <li><a href=\"#\">채용서비스 안내</a></li>\n");
      out.write("                    <li><a href=\"#\">제휴 및 배너광고 문의</a></li>\n");
      out.write("                    <li><a href=\"#\">이용약관</a></li>\n");
      out.write("                    <li><a href=\"#\">개인정보처리방침</a></li>\n");
      out.write("                    <li><a href=\"#\">위치기반서비스 이용약관</a></li>\n");
      out.write("                    <li><a href=\"#\" class=\"foot-row--out\">대한소방공제회</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <section class=\"foot-row--bg\">\n");
      out.write("        <div class=\"foot-row__wrap foot-row--isLeft\">\n");
      out.write("            <h2 class=\"foot-row__logo\">\n");
      out.write("                <a href=\"#\" class=\"foot-row__link\">\n");
      out.write("                    <img src=\"/img/logo_footer.svg\" alt=\"로고\" />\n");
      out.write("                </a>\n");
      out.write("            </h2>\n");
      out.write("            <div class=\"foot-row__text\">\n");
      out.write("                <p>대한소방공제회</p>\n");
      out.write("                <p>(05719) 서울시 송파구 송파대로 274, 4층(가락동)  대표전화 : 02-407-7119  FAX : 02-430-7459</p>\n");
      out.write("                <p><span>사업자등록번호 : XXX-XX-XXXXXX</span>부가통신사업 : 제XXXXXX호</p>\n");
      out.write("                <p><span>통신판매업신고 : 제2022-서울강남-XXXXX호</span>직업정보제공사업 신고번호 : 서울강남 제2022-XX호</p>\n");
      out.write("                <p>Copyright (c) Korea Fire Officials Credit Union All Rights Reserved.</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("</footer>\n");
      out.write("<script src=\"/js/common.js\"></script>\n");
      out.write("\n");
      out.write("\r\n");
      out.write("<script src=\"/js/allHeader.js\"></script>\r\n");
      out.write("<script src=\"/js/signup.js\"></script>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<!-- 뷰 컨트롤러 -->\r\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("	            ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/jsp/signup/../common/headerBase.jsp(26,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.loginVO}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            <a href=\"/login.do\" class=\"user-info__login\">로그인</a>\r\n");
          out.write("	            <a href=\"/signup.do\" class=\"user-info__join\">회원가입</a>\r\n");
          out.write("	            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                <a href=\"/logout.do\" class=\"user-info__login\">로그아웃</a>\r\n");
          out.write("	            ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/jsp/signup/../common/headerBase.jsp(46,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginVO.userType eq 'PERSONAL'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <button type=\"button\" class=\"primary_btn_icon ico_resume\" onclick=\"location.href='/psn/resume/registration.do';\">이력서 등록</button>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/jsp/signup/../common/headerBase.jsp(49,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginVO.userType eq 'COMPANY'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <button type=\"button\" class=\"sub_btn_icon ico_hire\" onclick=\"location.href='/com/jobopen/registration.do';\">채용공고 등록</button>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	               <button type=\"button\" class=\"primary_btn_icon ico_resume\" onclick=\"location.href='/psn/resume/registration.do';\">이력서 등록</button>\r\n");
          out.write("	               <button type=\"button\" class=\"sub_btn_icon ico_hire\" onclick=\"location.href='/com/jobopen/registration.do';\">채용공고 등록</button>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }
}
