/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-10-19 01:30:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.company;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/jsp/company/../common/top.jsp", Long.valueOf(1666072134445L));
    _jspx_dependants.put("/WEB-INF/jsp/company/../common/footer.jsp", Long.valueOf(1665638226418L));
    _jspx_dependants.put("/WEB-INF/jsp/company/../common/headerCompany.jsp", Long.valueOf(1666142577680L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1601362911995L));
    _jspx_dependants.put("jar:file:/C:/Users/simpl/workspace_kfors/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/frwk/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/jsp/company/../common/bottom.jsp", Long.valueOf(1665638226110L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--공통헤더-->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>JOB119 - 소방전문가 취업 플랫폼</title>\r\n");
      out.write("    <script src=\"/js/lib/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/common.css\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/additional-methods.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/company/index.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<article class=\"ad-top\">\r\n");
      out.write("    <div class=\"ad-top__close-btn\">\r\n");
      out.write("        <p>오늘 하루 보지 않기</p>\r\n");
      out.write("        <input type=\"checkbox\" />\r\n");
      out.write("    </div>\r\n");
      out.write("</article>\r\n");
      out.write("<header class=\"header-d\">\r\n");
      out.write("    <section class=\"head-wrap\">\r\n");
      out.write("        <h1 class=\"logo\">\r\n");
      out.write("            <a href=\"/index.do\" class=\"logo__link\">\r\n");
      out.write("                <img src=\"/img/logo.svg\" alt=\"로고\" />\r\n");
      out.write("            </a>\r\n");
      out.write("        </h1>\r\n");
      out.write("        <div class=\"search-area\">\r\n");
      out.write("            <div class=\"search-bar\">\r\n");
      out.write("                <button type=\"button\" class=\"search-bar__search-btn\"></button>\r\n");
      out.write("                <input type=\"text\" class=\"search-bar__textbar\" />\r\n");
      out.write("                <!-- <div class=\"search-bar__word\">\r\n");
      out.write("                    <a href=\"#\">소방시설</a>\r\n");
      out.write("                    <a href=\"#\">시설</a>\r\n");
      out.write("                    <a href=\"#\">건물관리</a>\r\n");
      out.write("                    <a href=\"#\">급구</a>\r\n");
      out.write("                </div> -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"user-info\">\r\n");
      out.write("            <a href=\"/logout.do\" class=\"user-info__login\">로그아웃</a>\r\n");
      out.write("            <a href=\"#\" class=\"user-info__join\">정보수정</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <nav class=\"head-nav\">\r\n");
      out.write("        <ul class=\"head-nav__depth-01\">\r\n");
      out.write("            <li class=\"sitemap head-nav__item-01\"><a href=\"/com/index.do\">기업MY홈</a></li>\r\n");
      out.write("            <li class=\"head-nav__item-01\"><a href=\"#\">채용공고 관리</a></li>\r\n");
      out.write("            <li class=\"head-nav__item-01\"><a href=\"#\">인재 관리</a></li>\r\n");
      out.write("            <li class=\"head-nav__item-01\"><a href=\"#\">MY채용정보</a></li>\r\n");
      out.write("            <li class=\"head-nav__item-01\"><a href=\"#\">취업서비스</a></li>\r\n");
      out.write("            <li class=\"head-nav__item-01\"><a href=\"#\">회원정보관리</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"head-btn\">\r\n");
      out.write("            <button type=\"button\" class=\"sub_btn_icon ico_hire\" onclick=\"location.href='/com/jobopen/registration.do'\">채용공고 등록</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mega-menu\">\r\n");
      out.write("            <div class=\"mega-menu__row\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>채용공고 관리</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"/com/jobopen/registration.do\">채용공고 등록</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"/com/jobopen/status.do\">채용공고 현황</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>인재 관리</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">지원자 현황</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>MY채용정보</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">맞춤 인재정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">스크랩 인재정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">우리기업 관심인재</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">맞춤 설정</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>취업서비스</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">채용공고 상품</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">이용내역</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>회원정보관리</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">기업회원정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">사업자 인증</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">인사담당자 정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">비밀번호 변경</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">정보수신 설정</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"mega-menu__bg\"></div>\r\n");
      out.write("</header>\r\n");
      out.write("<header class=\"header-m\">\r\n");
      out.write("    <section class=\"head-wrap\">\r\n");
      out.write("        <h1 class=\"logo\">\r\n");
      out.write("            <a href=\"#\" class=\"logo__link\">\r\n");
      out.write("                <img src=\"/img/logo.svg\" alt=\"로고\" />\r\n");
      out.write("            </a>\r\n");
      out.write("        </h1>\r\n");
      out.write("        <button type=\"button\" class=\"head-wrap__m-btn\"></button>\r\n");
      out.write("    </section>\r\n");
      out.write("    <nav class=\"m-nav\">\r\n");
      out.write("        <div class=\"m-nav__top\">\r\n");
      out.write("            <div class=\"user-info\">\r\n");
      out.write("                <a href=\"#\" class=\"user-info__login\">로그아웃</a>\r\n");
      out.write("                <a href=\"#\" class=\"user-info__join\">정보수정</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"button\" class=\"m-nav__close\"></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"m-nav__depth-01\">\r\n");
      out.write("            <li class=\"m-nav__item-01\"><a href=\"#\">채용공고 관리</a>\r\n");
      out.write("                <ul class=\"m-nav__depth-02\">\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">채용공고 등록</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">채용공고 현황</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"m-nav__item-01\"><a href=\"#\">인재 관리</a>\r\n");
      out.write("                <ul class=\"m-nav__depth-02\">\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">지원자 현황</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"m-nav__item-01\"><a href=\"#\">MY채용정보</a>\r\n");
      out.write("                <ul class=\"m-nav__depth-02\">\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">맞춤 인재정보</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">스크랩 인재정보</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">우리기업 관심인재</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">맞춤 설정</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"m-nav__item-01\"><a href=\"#\">취업서비스</a>\r\n");
      out.write("                <ul class=\"m-nav__depth-02\">\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">채용공고 상품</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">이용내역</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"m-nav__item-01\"><a href=\"#\">회원정보관리</a>\r\n");
      out.write("                <ul class=\"m-nav__depth-02\">\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">기업회원정보</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">사업자 인증</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">인사담당자 정보</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">비밀번호 변경</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">정보수신 설정</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"m-nav__head-btn\">\r\n");
      out.write("            <button type=\"button\" class=\"sub_btn_icon ico_hire\">채용공고 등록</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    <main class=\"main\">\r\n");
      out.write("        <section class=\"main__wrap\">\r\n");
      out.write("            <article class=\"box u-profile\">\r\n");
      out.write("                <div class=\"u-profile__top\">\r\n");
      out.write("                    <div class=\"user\">\r\n");
      out.write("                        <div class=\"user__l\">\r\n");
      out.write("                            <div class=\"user__picture\">\r\n");
      out.write("                                <img src=\"/img/conp_pic.png\" alt=\"기업회원 프로필 사진\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <button type=\"button\" class=\"user__pic-btn\"></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"user__r\">\r\n");
      out.write("                            <div class=\"user__user-info\">\r\n");
      out.write("                                <h2>포스코 119</h2>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"u-profile__state\">\r\n");
      out.write("                        <div class=\"u-profile__row\">\r\n");
      out.write("                            <p class=\"u-profile__title\">대표</p>\r\n");
      out.write("                            <p class=\"u-profile__nomal\">홍길동</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"u-profile__row\">\r\n");
      out.write("                            <p class=\"u-profile__title\">사업자등록증</p>\r\n");
      out.write("                            <p class=\"u-profile__nomal\">123456-123456</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"u-profile__row\">\r\n");
      out.write("                            <p class=\"u-profile__title\">기업인증완료</p>\r\n");
      out.write("                            <p class=\"u-profile__accent\"><strong>기업인증완료</strong>(인증일자 : 2022.01.09)</p>\r\n");
      out.write("                            <button type=\"button\" class=\"accent_btn\">바로가기</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"u-profile__row\">\r\n");
      out.write("                            <p class=\"u-profile__title\">등록 채용공고</p>\r\n");
      out.write("                            <p class=\"u-profile__accent\"><strong>5개</strong>(수정일자 : 2022.09.30)</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- <div class=\"u-profile__btn-wrap\">\r\n");
      out.write("                        <button type=\"button\" class=\"primary_btn_line u-profile__btn\">이력서 관리</button>\r\n");
      out.write("                    </div> -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"u-profile__bottom\">\r\n");
      out.write("                    <div class=\"user-now\">\r\n");
      out.write("                        <button type=\"button\" class=\"user-now__box\">\r\n");
      out.write("                            <h2 class=\"user-now__num\">3</h2>\r\n");
      out.write("                            <p class=\"user-now__kind\">진행중 공고</p>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button type=\"button\" class=\"user-now__box\">\r\n");
      out.write("                            <h2 class=\"user-now__num\">12</h2>\r\n");
      out.write("                            <p class=\"user-now__kind\">신규 지원자</p>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button type=\"button\" class=\"user-now__box\">\r\n");
      out.write("                            <h2 class=\"user-now__num\">2</h2>\r\n");
      out.write("                            <p class=\"user-now__kind\">미열람 이력서</p>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button type=\"button\" class=\"user-now__box\">\r\n");
      out.write("                            <h2 class=\"user-now__num\">8</h2>\r\n");
      out.write("                            <p class=\"user-now__kind\">스크랩 인재</p>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button type=\"button\" class=\"user-now__box\">\r\n");
      out.write("                            <h2 class=\"user-now__num\">8</h2>\r\n");
      out.write("                            <p class=\"user-now__kind\">이용서비스</p>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </article>\r\n");
      out.write("\r\n");
      out.write("            <article class=\"box\">\r\n");
      out.write("                <h3 class=\"box__title\">내 채용공고<span class=\"box__text\">총 <strong>2개</strong></span></h3>\r\n");
      out.write("                <div class=\"resume\">\r\n");
      out.write("                    <div class=\"resume__l\">\r\n");
      out.write("                        <h3 class=\"resume__title\">최고가 아닌 최선을 다하자는 신념으로 일하겠습니다.</h3>\r\n");
      out.write("                        <div class=\"resume__bottom\">\r\n");
      out.write("                            <div class=\"resume__text\">\r\n");
      out.write("                                <p>최종수정일</p>\r\n");
      out.write("                                <p>2022-08-10 11:00:55</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"resume__text\">\r\n");
      out.write("                                <p>등록일</p>\r\n");
      out.write("                                <p>2022-08-10 10:07:55</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"resume__text\">\r\n");
      out.write("                                <p>열람현황</p>\r\n");
      out.write("                                <p>3건</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"resume__btn-wrap\">\r\n");
      out.write("                        <button type=\"button\" class=\"primary_btn_line_s\">채용공고 수정</button>\r\n");
      out.write("                        <button type=\"button\" class=\"gray_btn_line\">채용공고 삭제</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"resume\">\r\n");
      out.write("                    <div class=\"resume__l\">\r\n");
      out.write("                        <h3 class=\"resume__title\">최고가 아닌 최선을 다하자는 신념으로 일하겠습니다.</h3>\r\n");
      out.write("                        <div class=\"resume__bottom\">\r\n");
      out.write("                            <div class=\"resume__text\">\r\n");
      out.write("                                <p>최종수정일</p>\r\n");
      out.write("                                <p>2022-08-25 16:00:55</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"resume__text\">\r\n");
      out.write("                                <p>등록일</p>\r\n");
      out.write("                                <p>2022-08-25 16:00:55</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"resume__text\">\r\n");
      out.write("                                <p>열람현황</p>\r\n");
      out.write("                                <p>3건</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"resume__btn-wrap\">\r\n");
      out.write("                        <button type=\"button\" class=\"primary_btn_line_s\">채용공고 수정</button>\r\n");
      out.write("                        <button type=\"button\" class=\"gray_btn_line\">채용공고 삭제</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"button\" class=\"primary_btn\" onclick=\"location.href='/com/jobopen/registration.do'\">채용공고 등록</button>\r\n");
      out.write("            </article>\r\n");
      out.write("\r\n");
      out.write("            <article class=\"box\">\r\n");
      out.write("                <h3 class=\"box__title\">채용공고 현황</h3>\r\n");
      out.write("                <div class=\"x_scroll\">\r\n");
      out.write("                    <table>\r\n");
      out.write("                        <colgroup>\r\n");
      out.write("                            <col style=\"width:10%\">\r\n");
      out.write("                            <col style=\"width:50%\">\r\n");
      out.write("                            <col style=\"width:10%\">\r\n");
      out.write("                            <col style=\"width:10%\">\r\n");
      out.write("                            <col style=\"width:10%\">\r\n");
      out.write("                            <col style=\"width:10%\">\r\n");
      out.write("                        </colgroup>\r\n");
      out.write("                        <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>공고일</th>\r\n");
      out.write("                            <th>채용공고 제목</th>\r\n");
      out.write("                            <th>마감일</th>\r\n");
      out.write("                            <th>지원방법</th>\r\n");
      out.write("                            <th colspan=\"2\">지원자 수</th>\r\n");
      out.write("                            <th></th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </article>\r\n");
      out.write("            <article class=\"box\">\r\n");
      out.write("                <h3 class=\"box__title\">추천인재정보</h3>\r\n");
      out.write("                <div class=\"x_scroll\">\r\n");
      out.write("                    <table>\r\n");
      out.write("                        <colgroup>\r\n");
      out.write("                            <col style=\"width:10%\">\r\n");
      out.write("                            <col style=\"width:50%\">\r\n");
      out.write("                            <col style=\"width:10%\">\r\n");
      out.write("                            <col style=\"width:10%\">\r\n");
      out.write("                            <col style=\"width:10%\">\r\n");
      out.write("                        </colgroup>\r\n");
      out.write("                        <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>지원일</th>\r\n");
      out.write("                            <th>공고내용</th>\r\n");
      out.write("                            <th>경력</th>\r\n");
      out.write("                            <th>학력</th>\r\n");
      out.write("                            <th colspan=\"2\">근무형태</th>\r\n");
      out.write("                            <th></th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>2022-10-11</td>\r\n");
      out.write("                            <td class=\"left\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <p class=\"t_strong\">한국전자금융(주) - 소방/방제 시설물 관리 ...</p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <p>담당업무 - 소방/방제 시설물 관리</p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>신입·경력</td>\r\n");
      out.write("                            <td>대학교</td>\r\n");
      out.write("                            <td class=\"no_border\">정규직</td>\r\n");
      out.write("                            <td class=\"hire_btn-wrap\">\r\n");
      out.write("                                <button type=\"button\" class=\"primary_btn_line\">스크랩</button>\r\n");
      out.write("                                <button type=\"button\" class=\"gray_btn_line\">맞춤 설정</button>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"button\" class=\"primary_btn\">맞춤 설정</button>\r\n");
      out.write("            </article>\r\n");
      out.write("\r\n");
      out.write("        </section><!-- main__wrap end -->\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script id=\"template\" type=\"x-tmpl-mustache\">\r\n");
      out.write("{{#data}}\r\n");
      out.write("<tr>\r\n");
      out.write("    <td>{{regDt}}</td>\r\n");
      out.write("    <td class=\"left\">\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("            <p class=\"t_strong\">한국전자금융(주) - {{title}}</p>\r\n");
      out.write("        </a>\r\n");
      out.write("        <p>{{reciArea}}</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td>{{openEndDt}}</td>\r\n");
      out.write("    <td>온라인</td>\r\n");
      out.write("    <td class=\"no_border\">\r\n");
      out.write("        <p><span class=\"t_accent\">11</span>명</p>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td class=\"hire_btn-wrap\">\r\n");
      out.write("        <button type=\"button\" class=\"primary_btn_line\">공고 수정</button>\r\n");
      out.write("        <button type=\"button\" class=\"gray_btn_line\">공고 마감</button>\r\n");
      out.write("    </td>\r\n");
      out.write("</tr>\r\n");
      out.write("{{/data}}\r\n");
      out.write("</script>\r\n");
      out.write("\n");
      out.write("<!--공통푸터-->\n");
      out.write("<footer>\n");
      out.write("    <section class=\"foot-row\">\n");
      out.write("        <div class=\"foot-row__wrap\">\n");
      out.write("            <div class=\"foot-row__btn-wrap\">\n");
      out.write("                <button type=\"button\" class=\"foot-row__btn\">\n");
      out.write("                    <img src=\"/img/ico_question.png\" alt=\"자주묻는질문 버튼\">\n");
      out.write("                    자주 묻는 질문</button>\n");
      out.write("                <button type=\"button\" class=\"foot-row__btn\">\n");
      out.write("                    <img src=\"/img/ico_ad.png\" alt=\"공고대행안내 버튼\">\n");
      out.write("                    공고대행 안내</button>\n");
      out.write("                <button type=\"button\" class=\"foot-row__btn\">\n");
      out.write("                    <img src=\"/img/ico_online.png\" alt=\"온라인문의 버튼\">\n");
      out.write("                    온라인 문의</button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"foot-row__num\">\n");
      out.write("                <p>고객센터</p>\n");
      out.write("                <p>1588-0000</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"foot-row__siste-info\">\n");
      out.write("                <p>평일 10:00 ~ 16:00</p>\n");
      out.write("                <p>주말·공휴일 휴무</p>\n");
      out.write("                <p>이메일 helpdesk@firework.or.kr</p>\n");
      out.write("                <p>팩스 02-XXXX-XXXX</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <section class=\"foot-row--bg\">\n");
      out.write("        <div class=\"foot-row__wrap\">\n");
      out.write("            <nav class=\"foot-row__nav\">\n");
      out.write("                <ul>\n");
      out.write("                    <li><a href=\"#\">사이트맵</a></li>\n");
      out.write("                    <li><a href=\"#\">상품안내</a></li>\n");
      out.write("                    <li><a href=\"#\">채용서비스 안내</a></li>\n");
      out.write("                    <li><a href=\"#\">제휴 및 배너광고 문의</a></li>\n");
      out.write("                    <li><a href=\"#\">이용약관</a></li>\n");
      out.write("                    <li><a href=\"#\">개인정보처리방침</a></li>\n");
      out.write("                    <li><a href=\"#\">위치기반서비스 이용약관</a></li>\n");
      out.write("                    <li><a href=\"#\" class=\"foot-row--out\">대한소방공제회</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <section class=\"foot-row--bg\">\n");
      out.write("        <div class=\"foot-row__wrap foot-row--isLeft\">\n");
      out.write("            <h2 class=\"foot-row__logo\">\n");
      out.write("                <a href=\"#\" class=\"foot-row__link\">\n");
      out.write("                    <img src=\"/img/logo_footer.svg\" alt=\"로고\" />\n");
      out.write("                </a>\n");
      out.write("            </h2>\n");
      out.write("            <div class=\"foot-row__text\">\n");
      out.write("                <p>대한소방공제회</p>\n");
      out.write("                <p>(05719) 서울시 송파구 송파대로 274, 4층(가락동)  대표전화 : 02-407-7119  FAX : 02-430-7459</p>\n");
      out.write("                <p><span>사업자등록번호 : XXX-XX-XXXXXX</span>부가통신사업 : 제XXXXXX호</p>\n");
      out.write("                <p><span>통신판매업신고 : 제2022-서울강남-XXXXX호</span>직업정보제공사업 신고번호 : 서울강남 제2022-XX호</p>\n");
      out.write("                <p>Copyright (c) Korea Fire Officials Credit Union All Rights Reserved.</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("</footer>\n");
      out.write("<script src=\"/js/common.js\"></script>\n");
      out.write("\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/js/otherHader.js\"></script>\r\n");
      out.write("<script src=\"/js/company/index.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/mustache.js/2.2.0/mustache.min.js\"></script>\r\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
