/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-10-19 03:48:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.personal;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/jsp/personal/../common/footer.jsp", Long.valueOf(1665638226418L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1601362911995L));
    _jspx_dependants.put("/WEB-INF/jsp/personal/../common/top.jsp", Long.valueOf(1666072134445L));
    _jspx_dependants.put("jar:file:/C:/Users/simpl/workspace_kfors/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/frwk/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/jsp/personal/../common/bottom.jsp", Long.valueOf(1665638226110L));
    _jspx_dependants.put("/WEB-INF/jsp/personal/../common/headerPersonal.jsp", Long.valueOf(1666072134425L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--공통헤더-->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>JOB119 - 소방전문가 취업 플랫폼</title>\r\n");
      out.write("    <script src=\"/js/lib/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/common.css\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/additional-methods.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/personal/userMyhome.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<article class=\"ad-top\">\r\n");
      out.write("    <div class=\"ad-top__close-btn\">\r\n");
      out.write("        <p>오늘 하루 보지 않기</p>\r\n");
      out.write("        <input type=\"checkbox\" />\r\n");
      out.write("    </div>\r\n");
      out.write("</article>\r\n");
      out.write("<header class=\"header-d\">\r\n");
      out.write("    <section class=\"head-wrap\">\r\n");
      out.write("        <h1 class=\"logo\">\r\n");
      out.write("            <a href=\"/index.do\" class=\"logo__link\">\r\n");
      out.write("                <img src=\"/img/logo.svg\" alt=\"로고\" />\r\n");
      out.write("            </a>\r\n");
      out.write("        </h1>\r\n");
      out.write("        <div class=\"search-area\">\r\n");
      out.write("            <div class=\"search-bar\">\r\n");
      out.write("                <button type=\"button\" class=\"search-bar__search-btn\"></button>\r\n");
      out.write("                <input type=\"text\" class=\"search-bar__textbar\" />\r\n");
      out.write("                <!-- <div class=\"search-bar__word\">\r\n");
      out.write("                    <a href=\"#\">소방시설</a>\r\n");
      out.write("                    <a href=\"#\">시설</a>\r\n");
      out.write("                    <a href=\"#\">건물관리</a>\r\n");
      out.write("                    <a href=\"#\">급구</a>\r\n");
      out.write("                </div> -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"user-info\">\r\n");
      out.write("            <a href=\"/logout.do\" class=\"user-info__login\">로그아웃</a>\r\n");
      out.write("            <a href=\"#\" class=\"user-info__join\">정보수정</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <nav class=\"head-nav\">\r\n");
      out.write("        <ul class=\"head-nav__depth-01\">\r\n");
      out.write("            <li class=\"sitemap head-nav__item-01\"><a href=\"/psn/index.do\">개인MY홈</a></li>\r\n");
      out.write("            <li class=\"head-nav__item-01\"><a href=\"#\">이력서 관리</a></li>\r\n");
      out.write("            <li class=\"head-nav__item-01\"><a href=\"#\">입사지원 관리</a></li>\r\n");
      out.write("            <li class=\"head-nav__item-01\"><a href=\"#\">MY맞춤정보</a></li>\r\n");
      out.write("            <li class=\"head-nav__item-01\"><a href=\"#\">취업서비스</a></li>\r\n");
      out.write("            <li class=\"head-nav__item-01\"><a href=\"#\">회원정보관리</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"head-btn\">\r\n");
      out.write("            <button type=\"button\" class=\"primary_btn_icon ico_resume\" onclick=\"location.href='/psn/resume/registration.do';\">이력서 등록</button>\r\n");
      out.write("            <!-- <button type=\"button\" class=\"sub_btn_icon ico_hire\">채용공고 등록</button> -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mega-menu\">\r\n");
      out.write("            <div class=\"mega-menu__row\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>이력서 관리</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"/psn/resume/registration.do\">이력서 등록</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">이력서 현황</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">인증 내역</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>입사지원 관리</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">입사지원 현황</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">이력서열람 현황</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">면접 제의</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">내 파일 관리</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>MY맞춤정보</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">맞춤 정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">스크랩 정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">관심기업 정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">맞춤 설정</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>취업서비스</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">적성 검사</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>회원정보관리</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">회원정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">비밀번호 변경</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">정보수신 설정</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">사용자제한 설정</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">간편로그인 관리</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"mega-menu__bg\"></div>\r\n");
      out.write("</header>\r\n");
      out.write("<header class=\"header-m\">\r\n");
      out.write("    <section class=\"head-wrap\">\r\n");
      out.write("        <h1 class=\"logo\">\r\n");
      out.write("            <a href=\"#\" class=\"logo__link\">\r\n");
      out.write("                <img src=\"/img/logo.svg\" alt=\"로고\" />\r\n");
      out.write("            </a>\r\n");
      out.write("        </h1>\r\n");
      out.write("        <button type=\"button\" class=\"head-wrap__m-btn\"></button>\r\n");
      out.write("    </section>\r\n");
      out.write("    <nav class=\"m-nav\">\r\n");
      out.write("        <div class=\"m-nav__top\">\r\n");
      out.write("            <div class=\"user-info\">\r\n");
      out.write("                <a href=\"#\" class=\"user-info__login\">로그아웃</a>\r\n");
      out.write("                <a href=\"#\" class=\"user-info__join\">정보수정</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"button\" class=\"m-nav__close\"></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"m-nav__depth-01\">\r\n");
      out.write("            <li class=\"m-nav__item-01\"><a href=\"#\">이력서 관리</a>\r\n");
      out.write("                <ul class=\"m-nav__depth-02\">\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"/psn/resume/registration.do\">이력서 등록</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">이력서 현황</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">인증 내역</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"m-nav__item-01\"><a href=\"#\">입사지원 관리</a>\r\n");
      out.write("                <ul class=\"m-nav__depth-02\">\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">입사지원 현황</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">이력서열람 현황</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">면접 제의</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">내 파일 관리</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"m-nav__item-01\"><a href=\"#\">MY맞춤정보</a>\r\n");
      out.write("                <ul class=\"m-nav__depth-02\">\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">맞춤 정보</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">스크랩 정보</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">관심기업 정보</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">맞춤 설정</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"m-nav__item-01\"><a href=\"#\">취업서비스</a>\r\n");
      out.write("                <ul class=\"m-nav__depth-02\">\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">적성 검사</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"m-nav__item-01\"><a href=\"#\">회원정보관리</a>\r\n");
      out.write("                <ul class=\"m-nav__depth-02\">\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">회원정보</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">비밀번호 변경</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">정보수신 설정</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">사용자제한 설정</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">간편로그인 관리</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"m-nav__head-btn\">\r\n");
      out.write("            <button type=\"button\" class=\"primary_btn_icon ico_resume\">이력서 등록</button>\r\n");
      out.write("            <!-- <button type=\"button\" class=\"sub_btn_icon ico_hire\">채용공고 등록</button> -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<main class=\"main\">\r\n");
      out.write("	<section class=\"main__wrap\">\r\n");
      out.write("	    <article class=\"box u-profile\">\r\n");
      out.write("	        <div class=\"u-profile__top\">\r\n");
      out.write("	            <div class=\"user\">\r\n");
      out.write("	                <div class=\"user__l\">\r\n");
      out.write("	                    <div class=\"user__picture\">\r\n");
      out.write("	                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/user_pic.png\" alt=\"개인회원 프로필 사진\">\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <button type=\"button\" class=\"user__pic-btn\"></button>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div class=\"user__r\">\r\n");
      out.write("	                    <div class=\"user__user-info\">\r\n");
      out.write("	                        <h2>홍길동 님</h2>\r\n");
      out.write("	                        <p>남자 55세 (1968 년생)</p>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"u-profile__state\">\r\n");
      out.write("	                <div class=\"u-profile__row\">\r\n");
      out.write("	                    <p class=\"u-profile__title\">퇴직소방관 인증</p>\r\n");
      out.write("	                    <p class=\"u-profile__accent\"><strong>인증완료</strong>(인증일자 : 2022.09.30)</p>\r\n");
      out.write("	                    <button type=\"button\" class=\"accent_btn\">바로가기</button>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div class=\"u-profile__row\">\r\n");
      out.write("	                    <p class=\"u-profile__title\">등록이력서</p>\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("	                    <!-- // 시연종료후 삭제 ********************** -->\r\n");
      out.write("	                    <p class=\"u-profile__accent\"><strong>3 개</strong>(인증일자 : 2022.09.30)</p>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"u-profile__btn-wrap\">\r\n");
      out.write("	                <button type=\"button\" class=\"primary_btn_line u-profile__btn\">이력서 관리</button>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div class=\"u-profile__bottom\">\r\n");
      out.write("	            <div class=\"user-now\">\r\n");
      out.write("	                <button type=\"button\" class=\"user-now__box\">\r\n");
      out.write("	                    <h2 class=\"user-now__num\">3</h2>\r\n");
      out.write("	                    <p class=\"user-now__kind\">입사지원</p>\r\n");
      out.write("	                </button>\r\n");
      out.write("	                <button type=\"button\" class=\"user-now__box\">\r\n");
      out.write("	                    <h2 class=\"user-now__num\">12</h2>\r\n");
      out.write("	                    <p class=\"user-now__kind\">이력서 열람</p>\r\n");
      out.write("	                </button>\r\n");
      out.write("	                <button type=\"button\" class=\"user-now__box\">\r\n");
      out.write("	                    <h2 class=\"user-now__num\">2</h2>\r\n");
      out.write("	                    <p class=\"user-now__kind\">면접 제의</p>\r\n");
      out.write("	                </button>\r\n");
      out.write("	                <button type=\"button\" class=\"user-now__box\">\r\n");
      out.write("	                    <h2 class=\"user-now__num\">8</h2>\r\n");
      out.write("	                    <p class=\"user-now__kind\">스크랩</p>\r\n");
      out.write("	                </button>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	    </article>\r\n");
      out.write("	    \r\n");
      out.write("	    <article class=\"box\">\r\n");
      out.write("	        <h3 class=\"box__title\">내 이력서<span class=\"box__text\">총 <strong>3개</strong></span></h3>\r\n");
      out.write("	       ");
      out.write("\r\n");
      out.write("	         <!-- // 시연종료후 삭제 ********************** -->\r\n");
      out.write("	        <div class=\"resume\">\r\n");
      out.write("	            <div class=\"resume__l\">\r\n");
      out.write("	                <h3 class=\"resume__title\" onclick=\"resumeModifyTest(3)\" style=\"cursor: pointer;\">소방설비기사 자격증 소지자, 소방설비를 책임지겠습니다.</h3>\r\n");
      out.write("	                <div class=\"resume__bottom\">\r\n");
      out.write("	                    <div class=\"resume__text\">\r\n");
      out.write("	                        <p>최종수정일</p>\r\n");
      out.write("	                        <p>2022-08-10 11:10</p>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"resume__text\">\r\n");
      out.write("	                        <p>등록일</p>\r\n");
      out.write("	                        <p>2022-08-10 11:10</p>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"resume__text\">\r\n");
      out.write("	                        <p>열람현황</p>\r\n");
      out.write("	                        <p>3건</p>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"resume__btn-wrap\">\r\n");
      out.write("	                <button type=\"button\" class=\"primary_btn_line_s\" onclick=\"resumeModifyTest(3)\">이력서 수정</button>\r\n");
      out.write("	                <button type=\"button\" class=\"gray_btn_line\">이력서 삭제</button>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div class=\"resume\">\r\n");
      out.write("	            <div class=\"resume__l\">\r\n");
      out.write("	                <h3 class=\"resume__title\" onclick=\"resumeModifyTest(2)\"  style=\"cursor: pointer;\">소방/방재 및 시설물관리 경험을 바탕으로 최선을 다하겠습니다.</h3>\r\n");
      out.write("	                <div class=\"resume__bottom\">\r\n");
      out.write("	                    <div class=\"resume__text\">\r\n");
      out.write("	                        <p>최종수정일</p>\r\n");
      out.write("	                        <p>2022-08-14 13:10</p>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"resume__text\">\r\n");
      out.write("	                        <p>등록일</p>\r\n");
      out.write("	                        <p>2022-08-14 10:07</p>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"resume__text\">\r\n");
      out.write("	                        <p>열람현황</p>\r\n");
      out.write("	                        <p>3건</p>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"resume__btn-wrap\">\r\n");
      out.write("	                <button type=\"button\" class=\"primary_btn_line_s\" onclick=\"resumeModifyTest(2)\">이력서 수정</button>\r\n");
      out.write("	                <button type=\"button\" class=\"gray_btn_line\">이력서 삭제</button>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div class=\"resume\">\r\n");
      out.write("	            <div class=\"resume__l\">\r\n");
      out.write("	                <h3 class=\"resume__title\" onclick=\"resumeModifyTest(1)\"  style=\"cursor: pointer;\">소방공무원 경력 30년의 준비된 소방안전관리자 입니다.</h3>\r\n");
      out.write("	                <div class=\"resume__bottom\">\r\n");
      out.write("	                    <div class=\"resume__text\">\r\n");
      out.write("	                        <p>최종수정일</p>\r\n");
      out.write("	                        <p>2022-08-25 16:00:55</p>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"resume__text\">\r\n");
      out.write("	                        <p>등록일</p>\r\n");
      out.write("	                        <p>2022-08-25 16:00:55</p>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"resume__text\">\r\n");
      out.write("	                        <p>열람현황</p>\r\n");
      out.write("	                        <p>3건</p>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"resume__btn-wrap\">\r\n");
      out.write("	                <button type=\"button\" class=\"primary_btn_line_s\" onclick=\"resumeModifyTest(1)\">이력서 수정</button>\r\n");
      out.write("	                <button type=\"button\" class=\"gray_btn_line\">이력서 삭제</button>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <button type=\"button\" class=\"primary_btn\" onclick=\"location.href='/psn/resume/registration.do';\">이력서 작성</button>\r\n");
      out.write("	    </article>\r\n");
      out.write("	\r\n");
      out.write("	    <article class=\"box\">\r\n");
      out.write("	        <h3 class=\"box__title\">입사지원 현황</h3>\r\n");
      out.write("	        <div class=\"x_scroll\">\r\n");
      out.write("	            <table>\r\n");
      out.write("	                <colgroup>\r\n");
      out.write("	                    <col style=\"width:10%\">\r\n");
      out.write("	                    <col style=\"width:36%\">\r\n");
      out.write("	                    <col style=\"width:10%\">\r\n");
      out.write("	                    <col style=\"width:10%\">\r\n");
      out.write("	                    <col style=\"width:10%\">\r\n");
      out.write("	                    <col style=\"width:12%\">\r\n");
      out.write("	                    <col style=\"width:12%\">\r\n");
      out.write("	                </colgroup>\r\n");
      out.write("	                <thead>\r\n");
      out.write("	                    <tr>\r\n");
      out.write("	                        <th>지원일</th>\r\n");
      out.write("	                        <th>회사명/공고제목</th>\r\n");
      out.write("	                        <th>지원분야</th>\r\n");
      out.write("	                        <th>마감일</th>\r\n");
      out.write("	                        <th>지원방법</th>\r\n");
      out.write("	                        <th colspan=\"2\">지원상태</th>\r\n");
      out.write("	                        <th></th>\r\n");
      out.write("	                    </tr>\r\n");
      out.write("	                </thead>\r\n");
      out.write("	                <tbody>\r\n");
      out.write("	                    <tr>\r\n");
      out.write("	                        <td>2022-09-08 14:06:25</td>\r\n");
      out.write("	                        <td class=\"left\">\r\n");
      out.write("	                            <a href=\"#\">\r\n");
      out.write("	                                <p class=\"t_strong\">한국전자금융(주) - 소방/방제 시설물 관리 ...</p>\r\n");
      out.write("	                            </a>\r\n");
      out.write("	                            <p>담당업무 - 소방/방제 시설물 관리</p>\r\n");
      out.write("	                        </td>\r\n");
      out.write("	                        <td>소방</td>\r\n");
      out.write("	                        <td>2022.09.22</td>\r\n");
      out.write("	                        <td>온라인</td>\r\n");
      out.write("	                        <td class=\"no_border\">\r\n");
      out.write("	                            <p class=\"t_strong\">지원 완료</p>\r\n");
      out.write("	                            <p class=\"t_accent\">열람</p>\r\n");
      out.write("	                        </td>\r\n");
      out.write("	                        <td>\r\n");
      out.write("	                            <button type=\"button\" class=\"gray_btn_line\">지원 취소</button>\r\n");
      out.write("	                        </td>\r\n");
      out.write("	                    </tr>\r\n");
      out.write("	                    <tr>\r\n");
      out.write("	                        <td>2022-09-08 14:06:25</td>\r\n");
      out.write("	                        <td class=\"left\">\r\n");
      out.write("	                            <a href=\"#\">\r\n");
      out.write("	                                <p class=\"t_strong\">한국전자금융(주) - 소방/방제 시설물 관리 ...</p>\r\n");
      out.write("	                            </a>\r\n");
      out.write("	                            <p>담당업무 - 소방/방제 시설물 관리</p>\r\n");
      out.write("	                        </td>\r\n");
      out.write("	                        <td>소방</td>\r\n");
      out.write("	                        <td>2022.09.22</td>\r\n");
      out.write("	                        <td>온라인</td>\r\n");
      out.write("	                        <td class=\"no_border\">\r\n");
      out.write("	                            <p class=\"t_strong\">지원 완료</p>\r\n");
      out.write("	                            <p class=\"t_gray\">미열람</p>\r\n");
      out.write("	                        </td>\r\n");
      out.write("	                        <td>\r\n");
      out.write("	                            <button type=\"button\" class=\"gray_btn_line\">지원 취소</button>\r\n");
      out.write("	                        </td>\r\n");
      out.write("	                    </tr>\r\n");
      out.write("	                </tbody>\r\n");
      out.write("	            </table>\r\n");
      out.write("	        </div>\r\n");
      out.write("	    </article>\r\n");
      out.write("	    <article class=\"box\">\r\n");
      out.write("	        <h3 class=\"box__title\">추천채용정보</h3>\r\n");
      out.write("	        <div class=\"x_scroll\">\r\n");
      out.write("	            <table>\r\n");
      out.write("	                <colgroup>\r\n");
      out.write("	                    <col style=\"width:10%\">\r\n");
      out.write("	                    <col style=\"width:46%\">\r\n");
      out.write("	                    <col style=\"width:12%\">\r\n");
      out.write("	                    <col style=\"width:12%\">\r\n");
      out.write("	                    <col style=\"width:10%\">\r\n");
      out.write("	                    <col style=\"width:10%\">\r\n");
      out.write("	                </colgroup>\r\n");
      out.write("	                <thead>\r\n");
      out.write("	                    <tr>\r\n");
      out.write("	                        <th>이름</th>\r\n");
      out.write("	                        <th>이력서 제목</th>\r\n");
      out.write("	                        <th>경력</th>\r\n");
      out.write("	                        <th>학력</th>\r\n");
      out.write("	                        <th colspan=\"2\">소방근무</th>\r\n");
      out.write("	                        <th></th>\r\n");
      out.write("	                    </tr>\r\n");
      out.write("	                </thead>\r\n");
      out.write("	                <tbody>\r\n");
      out.write("	                    <tr>\r\n");
      out.write("	                        <td>홍길동</td>\r\n");
      out.write("	                        <td class=\"left\">\r\n");
      out.write("	                            <a href=\"#\">\r\n");
      out.write("	                                <p class=\"t_strong\">한국전자금융(주) - 소방/방제 시설물 관리 ...</p>\r\n");
      out.write("	                            </a>\r\n");
      out.write("	                            <p>담당업무 - 소방/방제 시설물 관리</p>\r\n");
      out.write("	                        </td>\r\n");
      out.write("	                        <td>신입·경력</td>\r\n");
      out.write("	                        <td>고졸</td>\r\n");
      out.write("	                        <td class=\"no_border\">정규직</td>\r\n");
      out.write("	                        <td>\r\n");
      out.write("	                            <button type=\"button\" class=\"primary_btn_line\" onclick=\"alert('준비중입니다.');\">스크랩</button>\r\n");
      out.write("	                        </td>\r\n");
      out.write("	                    </tr>\r\n");
      out.write("	                </tbody>\r\n");
      out.write("	            </table>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <button type=\"button\" class=\"primary_btn\" onclick=\"alert('준비중입니다.');\">맞춤 조건 등록</button>\r\n");
      out.write("	    </article>\r\n");
      out.write("	</section><!-- main__wrap end -->\r\n");
      out.write("</main>\r\n");
      out.write("\n");
      out.write("<!--공통푸터-->\n");
      out.write("<footer>\n");
      out.write("    <section class=\"foot-row\">\n");
      out.write("        <div class=\"foot-row__wrap\">\n");
      out.write("            <div class=\"foot-row__btn-wrap\">\n");
      out.write("                <button type=\"button\" class=\"foot-row__btn\">\n");
      out.write("                    <img src=\"/img/ico_question.png\" alt=\"자주묻는질문 버튼\">\n");
      out.write("                    자주 묻는 질문</button>\n");
      out.write("                <button type=\"button\" class=\"foot-row__btn\">\n");
      out.write("                    <img src=\"/img/ico_ad.png\" alt=\"공고대행안내 버튼\">\n");
      out.write("                    공고대행 안내</button>\n");
      out.write("                <button type=\"button\" class=\"foot-row__btn\">\n");
      out.write("                    <img src=\"/img/ico_online.png\" alt=\"온라인문의 버튼\">\n");
      out.write("                    온라인 문의</button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"foot-row__num\">\n");
      out.write("                <p>고객센터</p>\n");
      out.write("                <p>1588-0000</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"foot-row__siste-info\">\n");
      out.write("                <p>평일 10:00 ~ 16:00</p>\n");
      out.write("                <p>주말·공휴일 휴무</p>\n");
      out.write("                <p>이메일 helpdesk@firework.or.kr</p>\n");
      out.write("                <p>팩스 02-XXXX-XXXX</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <section class=\"foot-row--bg\">\n");
      out.write("        <div class=\"foot-row__wrap\">\n");
      out.write("            <nav class=\"foot-row__nav\">\n");
      out.write("                <ul>\n");
      out.write("                    <li><a href=\"#\">사이트맵</a></li>\n");
      out.write("                    <li><a href=\"#\">상품안내</a></li>\n");
      out.write("                    <li><a href=\"#\">채용서비스 안내</a></li>\n");
      out.write("                    <li><a href=\"#\">제휴 및 배너광고 문의</a></li>\n");
      out.write("                    <li><a href=\"#\">이용약관</a></li>\n");
      out.write("                    <li><a href=\"#\">개인정보처리방침</a></li>\n");
      out.write("                    <li><a href=\"#\">위치기반서비스 이용약관</a></li>\n");
      out.write("                    <li><a href=\"#\" class=\"foot-row--out\">대한소방공제회</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <section class=\"foot-row--bg\">\n");
      out.write("        <div class=\"foot-row__wrap foot-row--isLeft\">\n");
      out.write("            <h2 class=\"foot-row__logo\">\n");
      out.write("                <a href=\"#\" class=\"foot-row__link\">\n");
      out.write("                    <img src=\"/img/logo_footer.svg\" alt=\"로고\" />\n");
      out.write("                </a>\n");
      out.write("            </h2>\n");
      out.write("            <div class=\"foot-row__text\">\n");
      out.write("                <p>대한소방공제회</p>\n");
      out.write("                <p>(05719) 서울시 송파구 송파대로 274, 4층(가락동)  대표전화 : 02-407-7119  FAX : 02-430-7459</p>\n");
      out.write("                <p><span>사업자등록번호 : XXX-XX-XXXXXX</span>부가통신사업 : 제XXXXXX호</p>\n");
      out.write("                <p><span>통신판매업신고 : 제2022-서울강남-XXXXX호</span>직업정보제공사업 신고번호 : 서울강남 제2022-XX호</p>\n");
      out.write("                <p>Copyright (c) Korea Fire Officials Credit Union All Rights Reserved.</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("</footer>\n");
      out.write("<script src=\"/js/common.js\"></script>\n");
      out.write("\n");
      out.write("\r\n");
      out.write("<!-- 뷰 컨트롤러 -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/otherHader.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/personal/personalIndex.js\"></script>\r\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
