/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-10-19 03:46:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/jsp/./common/footer.jsp", Long.valueOf(1665638226418L));
    _jspx_dependants.put("/WEB-INF/jsp/common/headerBase.jsp", Long.valueOf(1666087672666L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1601362911995L));
    _jspx_dependants.put("jar:file:/C:/Users/simpl/workspace_kfors/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/frwk/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/jsp/./common/top.jsp", Long.valueOf(1666072134445L));
    _jspx_dependants.put("/WEB-INF/jsp/./common/bottom.jsp", Long.valueOf(1665638226110L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--공통헤더-->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>JOB119 - 소방전문가 취업 플랫폼</title>\r\n");
      out.write("    <script src=\"/js/lib/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/common.css\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/additional-methods.min.js\"></script>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/main.css\">\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<article class=\"ad-top\">\r\n");
      out.write("    <div class=\"ad-top__close-btn\">\r\n");
      out.write("        <p>오늘 하루 보지 않기</p>\r\n");
      out.write("        <input type=\"checkbox\" />\r\n");
      out.write("    </div>\r\n");
      out.write("</article>\r\n");
      out.write("<header class=\"header-d\">\r\n");
      out.write("    <section class=\"head-wrap\">\r\n");
      out.write("        <h1 class=\"logo\">\r\n");
      out.write("            <a href=\"/\" class=\"logo__link\">\r\n");
      out.write("                <img src=\"/img/logo.svg\" alt=\"로고\" />\r\n");
      out.write("            </a>\r\n");
      out.write("        </h1>\r\n");
      out.write("        <div class=\"search-area\">\r\n");
      out.write("            <div class=\"search-bar\">\r\n");
      out.write("                <button type=\"button\" class=\"search-bar__search-btn\"></button>\r\n");
      out.write("                <input type=\"text\" class=\"search-bar__textbar\" />\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"user-info\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <nav class=\"head-nav\">\r\n");
      out.write("        <ul class=\"head-nav__depth-01\">\r\n");
      out.write("            <li class=\"sitemap head-nav__item-01\"><a href=\"#\">전체메뉴</a></li>\r\n");
      out.write("            <li class=\"head-nav__item-01 list-01\"><a href=\"#\">채용정보</a></li>\r\n");
      out.write("            <li class=\"head-nav__item-01 list-02\"><a href=\"#\">인재정보</a></li>\r\n");
      out.write("            <li class=\"head-nav__item-01\"><a href=\"#\">취업서비스</a></li>\r\n");
      out.write("            <li class=\"head-nav__item-01\"><a href=\"#\">맞춤정보</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"head-btn\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mega-menu all-menu sitemenu\">\r\n");
      out.write("            <div class=\"mega-menu__row all-menu__row\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p class=\"mega-menu__title all-menu__title\">전체메뉴</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>채용정보</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">일반채용</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">지역별 채용</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">분류별 채용</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">조건별 채용</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">맞춤 정보</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>인재정보</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">일반인재</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">전문인재</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">능력별인재</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">맞춤 정보</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>취업서비스</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">적성검사</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">채용광고상품</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>고객지원</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">공지사항</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">자주묻는질문</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">공고등록대행 안내</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">온라인 문의</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">채용서비스 안내</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">제휴 및 배너광고 문의</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">이용약관</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">개인정보처리방침</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">위치기반서비스 이용약관</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mega-menu all-menu menu-01\">\r\n");
      out.write("            <div class=\"mega-menu__row all-menu__row\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p class=\"mega-menu__title all-menu__title\">채용정보</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>일반채용</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">전체 채용공고</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">오늘 등록정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">마감임박 채용정보</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>지역별 채용</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02 all-menu__divide\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">전국</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">부산</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">대전</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">대구</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">세종</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">강원</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">충남</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">전남</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">경남</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">서울</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">인천</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">광주</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">울산</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">경기</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">충북</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">전북</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">경북</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">제주</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>분류별 채용</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">업종(소방)</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">업종(일반)</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">직무</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">자격</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>조건별 채용</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">고용형태</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">기업분류</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">직급/직책</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">우대사항</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">복리후생</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>맞춤 정보</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">맞춤 채용정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">스크랩 채용정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">오늘본 채용정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">맞춤 설정</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mega-menu all-menu menu-02\">\r\n");
      out.write("            <div class=\"mega-menu__row all-menu__row\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p class=\"mega-menu__title all-menu__title\">인재정보</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>일반인재</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">전체 인재정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">오늘 등록정보</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>전문인재</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">소방 자격증</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">소방관 근무경력</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">해외 근무경력</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">외국어 가능</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>능력별 인재</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">자격증별 인재</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">외국어가능별 인재</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">지역별 인재</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">경력조건별 인재</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <p>맞춤 정보</p>\r\n");
      out.write("                    <ul class=\"mega-menu__depth-02\">\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">맞춤 채용정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">오늘본 인재정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">스크랩 인재정보</a></li>\r\n");
      out.write("                        <li class=\"mega-menu__item-02\"><a href=\"#\">맞춤 설정</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"all-menu__bg\"></div>\r\n");
      out.write("</header>\r\n");
      out.write("<header class=\"header-m\">\r\n");
      out.write("    <section class=\"head-wrap\">\r\n");
      out.write("        <h1 class=\"logo\">\r\n");
      out.write("            <a href=\"#\" class=\"logo__link\">\r\n");
      out.write("                <img src=\"/img/logo.svg\" alt=\"로고\" />\r\n");
      out.write("            </a>\r\n");
      out.write("        </h1>\r\n");
      out.write("        <button type=\"button\" class=\"head-wrap__m-btn\"></button>\r\n");
      out.write("    </section>\r\n");
      out.write("    <nav class=\"m-nav\">\r\n");
      out.write("        <div class=\"m-nav__top\">\r\n");
      out.write("            <div class=\"user-info\">\r\n");
      out.write("                <a href=\"#\" class=\"user-info__login\">로그인</a>\r\n");
      out.write("                <a href=\"#\" class=\"user-info__join\">회원가입</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"button\" class=\"m-nav__close\"></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"m-nav__depth-01\">\r\n");
      out.write("            <li class=\"m-nav__item-01\"><a href=\"#\">채용정보</a>\r\n");
      out.write("                <ul class=\"m-nav__depth-02\">\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">일반 채용</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">지역별 채용</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">분류별 채용</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">조건별 채용</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">맞춤 정보</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"m-nav__item-01\"><a href=\"#\">인재정보</a>\r\n");
      out.write("                <ul class=\"m-nav__depth-02\">\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">일반 인재</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">전문 인재</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">능력별 인재</a></li>\r\n");
      out.write("                    <li class=\"m-nav__item-02\"><a href=\"#\">맞춤 정보</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"m-nav__item-01\"><a href=\"#\">취업서비스</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"m-nav__item-01\"><a href=\"#\">고객지원</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"m-nav__head-btn\">\r\n");
      out.write("            <button type=\"button\" class=\"primary_btn_icon ico_resume\" onclick=\"location.href='/psn/resume/registration.do';\">이력서 등록</button>\r\n");
      out.write("            <button type=\"button\" class=\"sub_btn_icon ico_hire\" onclick=\"location.href='/com/jobopen/registration.do';\">채용공고 등록</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<main class=\"main\">\r\n");
      out.write("    <section class=\"main__wrap\">\r\n");
      out.write("        <article class=\"area-01\">\r\n");
      out.write("            <div class=\"left\">\r\n");
      out.write("                <div class=\"ad-box\"></div>\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"box__title\">\r\n");
      out.write("                        <h3>키워드별 채용</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"keyword-cont\">\r\n");
      out.write("                        <button type=\"button\" class=\"primary_btn_line\">소방공무원</button>\r\n");
      out.write("                        <button type=\"button\" class=\"primary_btn_line\">소방</button>\r\n");
      out.write("                        <button type=\"button\" class=\"primary_btn_line\">소방안전관리자</button>\r\n");
      out.write("                        <button type=\"button\" class=\"primary_btn_line\">소방청</button>\r\n");
      out.write("                        <button type=\"button\" class=\"primary_btn_line\">소방설비기사</button>\r\n");
      out.write("                        <button type=\"button\" class=\"primary_btn_line\">소방교육</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"box__title\">\r\n");
      out.write("                        <h3>지역별 채용</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"area-cont\">\r\n");
      out.write("                        <button type=\"button\">서울</button>\r\n");
      out.write("                        <button type=\"button\">경기</button>\r\n");
      out.write("                        <button type=\"button\">인천</button>\r\n");
      out.write("                        <button type=\"button\">강원</button>\r\n");
      out.write("                        <button type=\"button\">대전</button>\r\n");
      out.write("                        <button type=\"button\">세종</button>\r\n");
      out.write("                        <button type=\"button\">충남</button>\r\n");
      out.write("                        <button type=\"button\">충북</button>\r\n");
      out.write("                        <button type=\"button\">부산</button>\r\n");
      out.write("                        <button type=\"button\">울산</button>\r\n");
      out.write("                        <button type=\"button\">경남</button>\r\n");
      out.write("                        <button type=\"button\">경북</button>\r\n");
      out.write("                        <button type=\"button\">대구</button>\r\n");
      out.write("                        <button type=\"button\">광주</button>\r\n");
      out.write("                        <button type=\"button\">전남</button>\r\n");
      out.write("                        <button type=\"button\">전북</button>\r\n");
      out.write("                        <button type=\"button\">제주</button>\r\n");
      out.write("                        <button type=\"button\">전국</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"right\">\r\n");
      out.write("				");
      if (_jspx_meth_c_005fchoose_005f2(_jspx_page_context))
        return;
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("        <article class=\"area-02 job\">\r\n");
      out.write("            <div class=\"area-02__top\">\r\n");
      out.write("                <h2>VVIP채용정보</h2>\r\n");
      out.write("                <a href=\"#\" class=\"more\">상품안내</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"area-02__cont\">\r\n");
      out.write("                <div class=\"job__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <img src=\"/img/main_vvip-01.jpg\" alt=\"VVIP채용공고 이미지-01\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>(주)서해소방공사</p>\r\n");
      out.write("                            <span>D-34</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>소방안전관리자 및 유틸리티 관리자 경력사원 모집 </h3>\r\n");
      out.write("                        <div class=\"bedge\">\r\n");
      out.write("                            <span>#충북 청주시</span>\r\n");
      out.write("                            <span>#신입·경력</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <img src=\"/img/main_vvip-02.jpg\" alt=\"VVIP채용공고 이미지-02\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>(주)현대글로비스</p>\r\n");
      out.write("                            <span>D-34</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>소방안전관리 팀장 및 팀원 모집</h3>\r\n");
      out.write("                        <div class=\"bedge\">\r\n");
      out.write("                            <span>#연봉 4,000만원</span>\r\n");
      out.write("                            <span>#경기 화성시</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <img src=\"/img/main_vvip-03.jpg\" alt=\"VVIP채용공고 이미지-03\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>(주)청명엔지니어링</p>\r\n");
      out.write("                            <span>D-34</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>[정규직] 소방관리&소방공사 채용공고</h3>\r\n");
      out.write("                        <div class=\"bedge\">\r\n");
      out.write("                            <span>#경남 양산시</span>\r\n");
      out.write("                            <span>#경력 무관</span>\r\n");
      out.write("                            <span>#정규직</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <img src=\"/img/main_vvip-04.jpg\" alt=\"VVIP채용공고 이미지-04\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>(주)아모텍</p>\r\n");
      out.write("                            <span>D-34</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>소방감리사 모십니다.</h3>\r\n");
      out.write("                        <div class=\"bedge\">\r\n");
      out.write("                            <span>#대전 유성구</span>\r\n");
      out.write("                            <span>#경력 1~3년</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <img src=\"/img/main_vvip-05.jpg\" alt=\"VVIP채용공고 이미지-05\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>(주)포스코케미칼</p>\r\n");
      out.write("                            <span>D-34</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>소방공사 전기팀 신입 및 경력직 모집 (필수 : 운전가능자)</h3>\r\n");
      out.write("                        <div class=\"bedge\">\r\n");
      out.write("                            <span>#고졸 이상</span>\r\n");
      out.write("                            <span>#경력무관</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <img src=\"/img/main_vvip-06.jpg\" alt=\"VVIP채용공고 이미지-06\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>용지로마스(주)</p>\r\n");
      out.write("                            <span>D-34</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>소방시설관리사 채용합니다.</h3>\r\n");
      out.write("                        <div class=\"bedge\">\r\n");
      out.write("                            <span>#계약직</span>\r\n");
      out.write("                            <span>#학력무관</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- <div class=\"area-02__btn\">\r\n");
      out.write("                <button type=\"button\" class=\" gray_btn_line\">더 많은 VVIP 채용정보 보기</button>\r\n");
      out.write("            </div> -->\r\n");
      out.write("        </article>\r\n");
      out.write("        <article class=\"area-02 job vip\">\r\n");
      out.write("            <div class=\"area-02__top\">\r\n");
      out.write("                <h2>VIP채용정보</h2>\r\n");
      out.write("                <a href=\"#\" class=\"more\">상품안내</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"area-02__cont\">\r\n");
      out.write("                <div class=\"job__item vip__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <img src=\"/img/main_vip-01.png\" alt=\"VIP이미지-01\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>한국국제협력단</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>2022 일반직·직원 채용</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <p class=\"date\">D-20</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item vip__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <img src=\"/img/main_vip-02.png\" alt=\"VIP이미지-02\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>참엔지리어링(주)</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>2022 하반기 사원 모집</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <p class=\"date\">D-20</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item vip__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <img src=\"/img/main_vip-03.png\" alt=\"VIP이미지-03\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>키엔스코리아(주)</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>각 부문 직원 채용</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <p class=\"date\">D-20</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item vip__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <img src=\"/img/main_vip-04.png\" alt=\"VIP이미지-04\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>LS그룹</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>2022 하반기 사원 모집</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <p class=\"date\">D-20</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item vip__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <img src=\"/img/main_vip-05.png\" alt=\"VIP이미지-05\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>유니셈(주)</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>반도체장비 유지보수 사원 모집</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <p class=\"date\">D-20</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item vip__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <img src=\"/img/main_vip-06.png\" alt=\"VIP이미지-06\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>중소기업기술정보진흥원</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>스마트한 인재 모집</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <p class=\"date\">D-20</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item vip__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <img src=\"/img/main_vip-07.png\" alt=\"VIP이미지-07\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>(주)신성이엔지</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>2022 하반기 사원 모집</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <p class=\"date\">D-20</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item vip__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <img src=\"/img/main_vip-08.png\" alt=\"VIP이미지-08\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>노벨리스코리아(주)</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>신입·경력 각 부분 모집</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <p class=\"date\">D-20</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item vip__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <img src=\"/img/main_vip-09.png\" alt=\"VIP이미지-09\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>(주)에스티오</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>2022 하반기 사원 모집</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <p class=\"date\">D-20</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item vip__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <img src=\"/img/main_vip-10.png\" alt=\"VIP이미지-10\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>(주)디알텍</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>2022 하반기 사원 모집</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <p class=\"date\">D-20</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("        <article class=\"area-02 job top\">\r\n");
      out.write("            <div class=\"area-02__top\">\r\n");
      out.write("                <h2>TOP채용정보</h2>\r\n");
      out.write("                <a href=\"#\" class=\"more\">상품안내</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"area-02__cont\">\r\n");
      out.write("                <div class=\"job__item top__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <img src=\"/img/main_top-01.png\" alt=\"TOP 이미지-01\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>(주)한익스프레스</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>시설물 유지보수 공무관..</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <p class=\"date\">D-20</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item top__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <img src=\"/img/main_top-02.png\" alt=\"TOP 이미지-02\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>LS그룹</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>2022 LS그룹 하반기 채용</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <p class=\"date\">D-20</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item top__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <img src=\"/img/main_top-03.png\" alt=\"TOP 이미지-03\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>(주)쌍곰</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>생산직 직원 모집</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <p class=\"date\">D-20</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item top__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <img src=\"/img/main_top-04.png\" alt=\"TOP 이미지-04\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>동광제약(주)</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>2022년 영업부 공개채용</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <p class=\"date\">D-20</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item top__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <img src=\"/img/main_top-05.png\" alt=\"TOP 이미지-05\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>LG그룹 D&O</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>레저사업부 신입/경력 채용</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <p class=\"date\">D-20</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"job__item top__item\">\r\n");
      out.write("                    <div class=\"pic\">\r\n");
      out.write("                        <img src=\"/img/main_top-06.png\" alt=\"TOP 이미지-06\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <div class=\"title__s\">\r\n");
      out.write("                            <p>(주)에스티오</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h3>STO 하반기 신입사원 모집</h3>\r\n");
      out.write("                        <button type=\"button\" class=\"btn_like\"></button>\r\n");
      out.write("                        <p class=\"date\">D-20</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("    </section>\r\n");
      out.write("</main>\r\n");
      out.write("<main>\r\n");
      out.write("    <section class=\"main__wrap\">\r\n");
      out.write("        <article class=\"area-02 job deadline\">\r\n");
      out.write("            <div class=\"area-02__top\">\r\n");
      out.write("                <h2>마감임박 채용공고</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"area-02__cont\">\r\n");
      out.write("                    <div class=\"job__item deadline__item\">\r\n");
      out.write("                        <div class=\"title\">\r\n");
      out.write("                            <div class=\"title__s\">\r\n");
      out.write("                                <p>(주)영원교육법인</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h3>[함영원 소방입시전문학원] 학원 강사 및 수강생 ...</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"date\">D-2</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"job__item deadline__item\">\r\n");
      out.write("                        <div class=\"title\">\r\n");
      out.write("                            <div class=\"title__s\">\r\n");
      out.write("                                <p>(주)베르티스</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h3>소방시설관리사 채용합니다.</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"date\">D-2</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"job__item deadline__item\">\r\n");
      out.write("                        <div class=\"title\">\r\n");
      out.write("                            <div class=\"title__s\">\r\n");
      out.write("                                <p>(주)이랜드리테일</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h3>소방감리사 모십니다.</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"date\">D-2</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"job__item deadline__item\">\r\n");
      out.write("                        <div class=\"title\">\r\n");
      out.write("                            <div class=\"title__s\">\r\n");
      out.write("                                <p>AK PLAZA(에이케이플라자)</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h3>소방공사 전기팀 신입 및 경력직 모집</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"date\">D-2</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("        </article>\r\n");
      out.write("        <article class=\"area-03\">\r\n");
      out.write("            <div class=\"left\">\r\n");
      out.write("                <h2>잡119 서비스</h2>\r\n");
      out.write("                <div class=\"service\">\r\n");
      out.write("                    <div class=\"service__item\">\r\n");
      out.write("                        <p>직업심리검사로<br>직업 적성을 찾으세요.</p>\r\n");
      out.write("                        <button type=\"button\">바로가기</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"service__item\">\r\n");
      out.write("                        <p>여러가지 상품들로<br>공고 효과를 극대화하세요.</p>\r\n");
      out.write("                        <button type=\"button\">바로가기</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"right\">\r\n");
      out.write("                <h2>잡119 정보 안내</h2>\r\n");
      out.write("                <div class=\"info_article\">\r\n");
      out.write("                    <p>그림으로 보는 취업 동향</p>\r\n");
      out.write("                    <div class=\"news\">\r\n");
      out.write("                        <div class=\"news__item\">\r\n");
      out.write("                            <img src=\"/img/main_news-01.png\" alt=\"취업동향-01\">\r\n");
      out.write("                            <p>친환경 이동수단,그리고</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"news__item\">\r\n");
      out.write("                            <img src=\"/img/main_news-02.png\" alt=\"취업동향-01\">\r\n");
      out.write("                            <p>친환경 이동수단,그리고</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"news__item\">\r\n");
      out.write("                            <img src=\"/img/main_news-03.png\" alt=\"취업동향-01\">\r\n");
      out.write("                            <p>친환경 이동수단,그리고</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("    </section>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("<!--공통푸터-->\n");
      out.write("<footer>\n");
      out.write("    <section class=\"foot-row\">\n");
      out.write("        <div class=\"foot-row__wrap\">\n");
      out.write("            <div class=\"foot-row__btn-wrap\">\n");
      out.write("                <button type=\"button\" class=\"foot-row__btn\">\n");
      out.write("                    <img src=\"/img/ico_question.png\" alt=\"자주묻는질문 버튼\">\n");
      out.write("                    자주 묻는 질문</button>\n");
      out.write("                <button type=\"button\" class=\"foot-row__btn\">\n");
      out.write("                    <img src=\"/img/ico_ad.png\" alt=\"공고대행안내 버튼\">\n");
      out.write("                    공고대행 안내</button>\n");
      out.write("                <button type=\"button\" class=\"foot-row__btn\">\n");
      out.write("                    <img src=\"/img/ico_online.png\" alt=\"온라인문의 버튼\">\n");
      out.write("                    온라인 문의</button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"foot-row__num\">\n");
      out.write("                <p>고객센터</p>\n");
      out.write("                <p>1588-0000</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"foot-row__siste-info\">\n");
      out.write("                <p>평일 10:00 ~ 16:00</p>\n");
      out.write("                <p>주말·공휴일 휴무</p>\n");
      out.write("                <p>이메일 helpdesk@firework.or.kr</p>\n");
      out.write("                <p>팩스 02-XXXX-XXXX</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <section class=\"foot-row--bg\">\n");
      out.write("        <div class=\"foot-row__wrap\">\n");
      out.write("            <nav class=\"foot-row__nav\">\n");
      out.write("                <ul>\n");
      out.write("                    <li><a href=\"#\">사이트맵</a></li>\n");
      out.write("                    <li><a href=\"#\">상품안내</a></li>\n");
      out.write("                    <li><a href=\"#\">채용서비스 안내</a></li>\n");
      out.write("                    <li><a href=\"#\">제휴 및 배너광고 문의</a></li>\n");
      out.write("                    <li><a href=\"#\">이용약관</a></li>\n");
      out.write("                    <li><a href=\"#\">개인정보처리방침</a></li>\n");
      out.write("                    <li><a href=\"#\">위치기반서비스 이용약관</a></li>\n");
      out.write("                    <li><a href=\"#\" class=\"foot-row--out\">대한소방공제회</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <section class=\"foot-row--bg\">\n");
      out.write("        <div class=\"foot-row__wrap foot-row--isLeft\">\n");
      out.write("            <h2 class=\"foot-row__logo\">\n");
      out.write("                <a href=\"#\" class=\"foot-row__link\">\n");
      out.write("                    <img src=\"/img/logo_footer.svg\" alt=\"로고\" />\n");
      out.write("                </a>\n");
      out.write("            </h2>\n");
      out.write("            <div class=\"foot-row__text\">\n");
      out.write("                <p>대한소방공제회</p>\n");
      out.write("                <p>(05719) 서울시 송파구 송파대로 274, 4층(가락동)  대표전화 : 02-407-7119  FAX : 02-430-7459</p>\n");
      out.write("                <p><span>사업자등록번호 : XXX-XX-XXXXXX</span>부가통신사업 : 제XXXXXX호</p>\n");
      out.write("                <p><span>통신판매업신고 : 제2022-서울강남-XXXXX호</span>직업정보제공사업 신고번호 : 서울강남 제2022-XX호</p>\n");
      out.write("                <p>Copyright (c) Korea Fire Officials Credit Union All Rights Reserved.</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("</footer>\n");
      out.write("<script src=\"/js/common.js\"></script>\n");
      out.write("\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<script src=\"/js/allHeader.js\"></script>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("	            ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/jsp/common/headerBase.jsp(26,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.loginVO}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            <a href=\"/login.do\" class=\"user-info__login\">로그인</a>\r\n");
          out.write("	            <a href=\"/signup.do\" class=\"user-info__join\">회원가입</a>\r\n");
          out.write("	            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                <a href=\"/logout.do\" class=\"user-info__login\">로그아웃</a>\r\n");
          out.write("	            ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/jsp/common/headerBase.jsp(46,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginVO.userType eq 'PERSONAL'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <button type=\"button\" class=\"primary_btn_icon ico_resume\" onclick=\"location.href='/psn/resume/registration.do';\">이력서 등록</button>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/jsp/common/headerBase.jsp(49,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginVO.userType eq 'COMPANY'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <button type=\"button\" class=\"sub_btn_icon ico_hire\" onclick=\"location.href='/com/jobopen/registration.do';\">채용공고 등록</button>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	               <button type=\"button\" class=\"primary_btn_icon ico_resume\" onclick=\"location.href='/psn/resume/registration.do';\">이력서 등록</button>\r\n");
          out.write("	               <button type=\"button\" class=\"sub_btn_icon ico_hire\" onclick=\"location.href='/com/jobopen/registration.do';\">채용공고 등록</button>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f2_reused = false;
    try {
      _jspx_th_c_005fchoose_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f2.setParent(null);
      int _jspx_eval_c_005fchoose_005f2 = _jspx_th_c_005fchoose_005f2.doStartTag();
      if (_jspx_eval_c_005fchoose_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                ");
          if (_jspx_meth_c_005fwhen_005f3(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("	                ");
          if (_jspx_meth_c_005fwhen_005f4(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          if (_jspx_meth_c_005fotherwise_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("	            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
      _jspx_th_c_005fchoose_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f3 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f3_reused = false;
    try {
      _jspx_th_c_005fwhen_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      // /WEB-INF/jsp/index.jsp(57,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginVO.userType eq 'PERSONAL'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f3 = _jspx_th_c_005fwhen_005f3.doStartTag();
      if (_jspx_eval_c_005fwhen_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                    <div class=\"box login\">\r\n");
          out.write("	                        <div class=\"login__profile\">\r\n");
          out.write("	                            <div class=\"profile_left\">\r\n");
          out.write("	                                <div class=\"profile_pic\">\r\n");
          out.write("	                                    <img src=\"/img/user_pic.png\" alt=\"유저이미지\">\r\n");
          out.write("	                                </div>\r\n");
          out.write("	                            </div>\r\n");
          out.write("	                            <div class=\"profile_right\">\r\n");
          out.write("	                                <h3 class=\"name\">홍길동</h3>\r\n");
          out.write("	                                <button type=\"button\" onclick=\"location.href='/psn/index.do';\" class=\"primary_btn_line\">이력서 관리</button>\r\n");
          out.write("	                                <p>(수정일 2022.10.05)</p>\r\n");
          out.write("	                            </div>\r\n");
          out.write("	                        </div>\r\n");
          out.write("	                        <div class=\"login__sub\">\r\n");
          out.write("	                            <a href=\"#\">지원현황</a>\r\n");
          out.write("	                            <a href=\"#\">열람기업</a>\r\n");
          out.write("	                            <a href=\"#\">스크랩</a>\r\n");
          out.write("	                            <a href=\"#\">최근 본 공고</a>\r\n");
          out.write("	                        </div>\r\n");
          out.write("	                    </div>\r\n");
          out.write("	                    <div class=\"box board-info main_btns\">\r\n");
          out.write("	                        <button type=\"button\" class=\"primary_btn\">인재서비스 적성 검사 받기</button>\r\n");
          out.write("	                        <button type=\"button\" class=\"accent_btn\">퇴직소방관 경력인증제</button>\r\n");
          out.write("	                        <button type=\"button\" class=\"primary_btn\">구인기업회원 인증방법</button>\r\n");
          out.write("	                    </div>\r\n");
          out.write("	                ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f3);
      _jspx_th_c_005fwhen_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f4 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f4_reused = false;
    try {
      _jspx_th_c_005fwhen_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      // /WEB-INF/jsp/index.jsp(84,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginVO.userType eq 'COMPANY'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f4 = _jspx_th_c_005fwhen_005f4.doStartTag();
      if (_jspx_eval_c_005fwhen_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                    <div class=\"box login\">\r\n");
          out.write("	                        <div class=\"login__profile\">\r\n");
          out.write("	                            <div class=\"profile_left\">\r\n");
          out.write("	                                <div class=\"profile_pic\">\r\n");
          out.write("	                                    <img src=\"/img/user_pic.png\" alt=\"유저이미지\">\r\n");
          out.write("	                                </div>\r\n");
          out.write("	                            </div>\r\n");
          out.write("	                            <div class=\"profile_right\">\r\n");
          out.write("	                                <h3 class=\"name\">(주)기업</h3>\r\n");
          out.write("	                                <button type=\"button\" onclick=\"location.href='/com/index.do';\" class=\"sub_btn_line\">채용공고 관리</button>\r\n");
          out.write("	                                <p>(수정일 2022.10.05)</p>\r\n");
          out.write("	                            </div>\r\n");
          out.write("	                        </div>\r\n");
          out.write("	                        <div class=\"login__sub\">\r\n");
          out.write("	                            <a href=\"#\">지원현황</a>\r\n");
          out.write("	                            <a href=\"#\">열람기업</a>\r\n");
          out.write("	                            <a href=\"#\">스크랩</a>\r\n");
          out.write("	                            <a href=\"#\">최근 본 인재</a>\r\n");
          out.write("	                        </div>\r\n");
          out.write("	                    </div>\r\n");
          out.write("	                    <div class=\"box board-info main_btns\">\r\n");
          out.write("	                        <button type=\"button\" class=\"primary_btn\">인재서비스 적성 검사 받기</button>\r\n");
          out.write("	                        <button type=\"button\" class=\"accent_btn\">퇴직소방관 경력인증제</button>\r\n");
          out.write("	                        <button type=\"button\" class=\"primary_btn\">구인기업회원 인증방법</button>\r\n");
          out.write("	                    </div>\r\n");
          out.write("	                ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f4);
      _jspx_th_c_005fwhen_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f2 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f2_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      int _jspx_eval_c_005fotherwise_005f2 = _jspx_th_c_005fotherwise_005f2.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<div class=\"box login\">\r\n");
          out.write("		                    <button type=\"button\" onclick=\"location.href='/login.do';\" >개인회원<br>로그인</button>\r\n");
          out.write("		                    <button type=\"button\" onclick=\"location.href='/login.do';\" >기업회원<br>로그인</button>\r\n");
          out.write("		                    <div class=\"login__sub\">\r\n");
          out.write("		                    	<a href=\"/login.do\" class=\"user-info__login\">로그인</a>\r\n");
          out.write("		            			<a href=\"/signup.do\" class=\"user-info__join\">회원가입</a>\r\n");
          out.write("		                    </div>\r\n");
          out.write("		                </div>\r\n");
          out.write("		                <div class=\"box board-info\">\r\n");
          out.write("		                    <div class=\"box__title\">\r\n");
          out.write("		                        <h3>공지사항·이벤트</h3>\r\n");
          out.write("		                    </div>\r\n");
          out.write("		                    <ul>\r\n");
          out.write("		                        <li><a href=\"#\">[공지] 퇴직 소방관 인증받는 방법을 알려드립니다.</a></li>\r\n");
          out.write("		                        <li><a href=\"#\">[이벤트] 오픈 이벤트 관련한 공지사항</a></li>\r\n");
          out.write("		                        <li><a href=\"#\">[공지] 2022 하반기 대한소방공제회 신입채용...</a></li>\r\n");
          out.write("		                    </ul>\r\n");
          out.write("		                </div>\r\n");
          out.write("	                ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f2);
      _jspx_th_c_005fotherwise_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f2_reused);
    }
    return false;
  }
}
